const transformDispensary = input => {
  const result = [];

  for (const stateName in input) {
    const stateObject = input[stateName];

    const stateItem = {
      id: stateName,
      name: stateName,
      districts: [],
    };

    for (const districtName in stateObject) {
      const districtArray = stateObject[districtName];

      const districtItem = {
        id: districtName,
        name: districtName,
        dispensary: districtArray.map(dispensaryName => ({
          id: dispensaryName,
          name: dispensaryName,
        })),
      };

      stateItem.districts.push(districtItem);
    }

    result.push(stateItem);
  }

  return result;
};

export const stateDistrictDispensary = transformDispensary(dispensaryJson);

export const cityOptions = [
  {
    id: 'Noida',
    name: 'Noida',
  },
  {
    id: 'Bhangel',
    name: 'Bhangel',
  },
  {
    id: 'Greater Noida',
    name: 'Greater Noida',
  },
  {
    id: 'Ghaziabad',
    name: 'Ghaziabad',
  },
];

export const maritialOptions = [
  {id: 'Married', name: 'Married'},
  {id: 'Unmarried', name: 'Unmarried'},
  {id: 'Divorced', name: 'Divorced'},
];
export const workShift = [
  {id: 'nightShift', name: 'Night shift'},
  {id: 'dayShift', name: 'Day shift'},
];

export const sortOption = [
  {id: 'lowToHigh', name: 'Low to high salary'},
  {id: 'highToLow', name: 'High to low salary'},
];

export const accountType = [
  {id: 'Savings', name: 'Savings'},
  {id: 'Current', name: 'Current'},
  {id: 'Others', name: 'Others'},
];
export const genderOptions = [
  {
    id: 'male',
    name: 'Male',
  },
  {
    id: 'female',
    name: 'Female',
  },
  {
    id: 'others',
    name: 'Others',
  },
];

export const departments = [
  // Skilled Departments
  {
    id: 'manufacturing',
    name: 'Manufacturing and Production',
    jobs: [
      {
        id: 'welder',
        name: 'Welder',
      },
      {
        id: 'cnc_machinist',
        name: 'CNC Machinist',
      },
      {
        id: 'electrician',
        name: 'Electrician',
      },
      {
        id: 'tool_and_die_maker',
        name: 'Tool and Die Maker',
      },
      {
        id: 'industrial_mechanic',
        name: 'Industrial Mechanic',
      },
      // Add more job titles as needed
    ],
  },
  {
    id: 'engineering',
    name: 'Engineering and Technical',
    jobs: [
      {
        id: 'software_engineer',
        name: 'Software Engineer',
      },
      {
        id: 'civil_engineer',
        name: 'Civil Engineer',
      },
      {
        id: 'mechanical_engineer',
        name: 'Mechanical Engineer',
      },
      {
        id: 'electronics_technician',
        name: 'Electronics Technician',
      },
      {
        id: 'quality_control_engineer',
        name: 'Quality Control Engineer',
      },
      // Add more job titles as needed
    ],
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    jobs: [
      {
        id: 'registered_nurse',
        name: 'Registered Nurse',
      },
      {
        id: 'radiology_technician',
        name: 'Radiology Technician',
      },
      {
        id: 'surgical_technologist',
        name: 'Surgical Technologist',
      },
      {
        id: 'pharmacist',
        name: 'Pharmacist',
      },
      {
        id: 'dental_hygienist',
        name: 'Dental Hygienist',
      },
      // Add more job titles as needed
    ],
  },
  {
    id: 'it',
    name: 'Information Technology',
    jobs: [
      {
        id: 'software_developer',
        name: 'Software Developer',
      },
      {
        id: 'network_administrator',
        name: 'Network Administrator',
      },
      {
        id: 'database_administrator',
        name: 'Database Administrator',
      },
      {
        id: 'systems_analyst',
        name: 'Systems Analyst',
      },
      {
        id: 'cybersecurity_specialist',
        name: 'Cybersecurity Specialist',
      },
      // Add more job titles as needed
    ],
  },

  // Semi-Skilled Departments
  {
    id: 'logistics',
    name: 'Logistics',
    jobs: [
      {
        id: 'assembler',
        name: 'Assembler',
      },
      {
        id: 'line_worker',
        name: 'Line Worker',
      },
      {
        id: 'forklift_operator',
        name: 'Forklift Operator',
      },
      {
        id: 'packer',
        name: 'Packer',
      },
      // Add more job titles as needed
    ],
  },
  {
    id: 'construction',
    name: 'Construction and Trades',
    jobs: [
      {
        id: 'carpenter',
        name: 'Carpenter',
      },
      {
        id: 'plumber',
        name: 'Plumber',
      },
      {
        id: 'electrician',
        name: 'Electrician',
      },
      {
        id: 'mason',
        name: 'Mason',
      },
      {
        id: 'welder',
        name: 'Welder',
      },
      // Add more job titles as needed
    ],
  },
  {
    id: 'transportation',
    name: 'Transportation and Logistics',
    jobs: [
      {
        id: 'truck_driver',
        name: 'Truck Driver',
      },
      {
        id: 'warehouse_associate',
        name: 'Warehouse Associate',
      },
      {
        id: 'delivery_driver',
        name: 'Delivery Driver',
      },
      {
        id: 'material_handler',
        name: 'Material Handler',
      },
      {
        id: 'order_picker',
        name: 'Order Picker',
      },
      // Add more job titles as needed
    ],
  },
  {
    id: 'hospitality',
    name: 'Hospitality and Service',
    jobs: [
      {
        id: 'chef_cook',
        name: 'Chef/Cook',
      },
      {
        id: 'waitstaff',
        name: 'Waitstaff',
      },
      {
        id: 'barista',
        name: 'Barista',
      },
      {
        id: 'housekeeper',
        name: 'Housekeeper',
      },
      {
        id: 'bartender',
        name: 'Bartender',
      },
      // Add more job titles as needed
    ],
  },

  // Unskilled Departments
  {
    id: 'general_labor',
    name: 'General Labor',
    jobs: [
      {
        id: 'laborer',
        name: 'Laborer',
      },
      {
        id: 'groundskeeper',
        name: 'Groundskeeper',
      },
      {
        id: 'cleaner',
        name: 'Cleaner',
      },
      {
        id: 'janitor',
        name: 'Janitor',
      },
      {
        id: 'farm_worker',
        name: 'Farm Worker',
      },
      // Add more job titles as needed
    ],
  },
  {
    id: 'retail',
    name: 'Retail and Customer Service',
    jobs: [
      {
        id: 'cashier',
        name: 'Cashier',
      },
      {
        id: 'retail_sales_associate',
        name: 'Retail Sales Associate',
      },
      {
        id: 'stock_clerk',
        name: 'Stock Clerk',
      },
      {
        id: 'customer_service_representative',
        name: 'Customer Service Representative',
      },
      // Add more job titles as needed
    ],
  },
  {
    id: 'food_service',
    name: 'Food Service',
    jobs: [
      {
        id: 'dishwasher',
        name: 'Dishwasher',
      },
      {
        id: 'fast_food_crew',
        name: 'Fast Food Crew',
      },
      {
        id: 'food_prep_worker',
        name: 'Food Prep Worker',
      },
      {
        id: 'busser',
        name: 'Busser',
      },
      // Add more job titles as needed
    ],
  },
];

export const dispensaryJson = {
  'Andaman and Nicobar': {
    Nicobar: [],
    'North and Middle Andaman': [],
    'South Andaman': ['Jungli Ghat, Port Blair, AN (ESIS Disp.)'],
  },
  'Andhra Pradesh': {
    Ananthpuram: [
      'Ananthapur, AP (ESIS Disp.)',
      'Guntakal, AP (ESIS Disp.)',
      'Tadipatri, AP (ESIS Disp.)',
      'Ananthapur, AP (ESIS Disp.)',
      'Hindupur, AP (ESIS Disp.)',
      'Tadipatri, AP (ESIS Disp.)',
    ],
    Annamayya: ['Madanapalli, AP (ESIS Disp.)', 'Rly Kodur, AP (ESIS Disp.)'],
    Chitoor: [
      'Chittor, AP (ESIS Disp.)',
      'Nagari, AP (ESIS Disp.)',
      'Bangarupalyam, AP (ESIS Disp.)',
      'Renigunta, AP (ESIS Disp.)',
      'Tirupathi, AP (ESIS Disp.)',
      'Satyavedu, AP (ESIS Disp.)',
      'Puthalapattu, AP (ESIS Disp.)',
      'Varadaiahpalem, AP (ESIS Disp.)',
    ],
    'East Godawari': [
      'Dowleswaram, AP (ESIS Disp.)',
      'Kadiyam, AP (ESIS Disp.)',
      'Kakinada, AP (ESIS Disp.)',
      'Lalacheruvu, AP (ESIS Disp.)',
      'Innispeta, AP (ESIS Disp.)',
      'Seethampeta, AP (ESIS Disp.)',
      'Samalkot, AP (ESIS Disp.)',
      'Sarpavaram, AP (ESIS Disp.)',
      'Tuni, AP (ESIS Disp.)',
    ],
    Guntur: [
      'Undavalli AP (ESIS Disp.)',
      'Pedakakani AP (ESIS Disp.)',
      'P.V. Thota AP (ESIS Disp.)',
      'Devapuram AP (ESIS Disp.)',
      'Nallapadu AP (ESIS Dispensary) AP',
      'Guntakal, AP (ESIS Disp.)',
      'K.Nagar, AP (ESIS Disp.)',
      'Nallapadu, AP (ESIS Disp.)',
      'Pedakakani, AP (ESIS Disp.)',
      'P.V.Thota, AP (ESIS Disp.)',
      'Undavalli, AP (ESIS Disp.)',
      'Kotnur, AP (ESIS Disp.)',
      'Macherla, AP (ESIS Disp.)',
      'DCBO - Guntur',
      'Ganapavaram, AP (ESIS Disp.)',
    ],
    Kadapa: [
      'Kadapa, AP (ESIS Disp.)',
      'Proddutur, AP (ESIS Disp.)',
      'Yerraguntla, AP (ESIS Disp.)',
    ],
    Kakinada: [],
    Krishna: [
      'Gangoor, AP (ESIS Disp.)',
      'Bapulapadu, AP (ESIS Disp.)',
      'Sattenapalli, AP (ESIS Disp.)',
      'Machilipatnam, AP (ESIS Disp.)',
      'Vijayawada West, AP (ESIS Disp.)',
      'Gunadala, AP (ESIS Disp.)',
      'Vijayawada Town, AP (ESIS Disp.)',
      'Vijayawada East, AP (ESIS Disp.)',
      'Vijayawada ACC, AP (ESIS Disp.)',
      'Vijayawada MPF, AP (ESIS Disp.)',
      'Kondapalli, AP (ESIS Disp.)',
      'Jaggaiahpeta, AP (ESIS Disp.)',
      'Bapulapadu, AP (ESIS Disp.)',
      'Gangoor, AP (ESIS Disp.)',
      'Jaggaiahpeta, AP (ESIS Disp.)',
      'Kondapalli, AP (ESIS Disp.)',
      'Machilipatnam, AP (ESIS Disp.)',
      'Gunadala, AP (ESIS Disp.)',
      'Vijayawada East, AP (ESIS Disp.)',
      'Vijayawada Town, AP (ESIS Disp.)',
      'Vijayawada ACC, AP (ESIS Disp.)',
      'Vijayawada MPF, AP (ESIS Disp.)',
      'Kanchikacherla, AP (ESIS Disp.)',
      'Appannaveedu, AP (ESIS Disp.)',
    ],
    Kurnool: [
      'Adoni (West), AP (ESIS Disp.)',
      'Adoni (East), AP (ESIS Disp.)',
      'Budhawarpet, AP (ESIS Disp.)',
      'Nandyal, AP (ESIS Disp.)',
      'Yemmiganur, AP (ESIS Disp.)',
    ],
    Nandyal: ['Nandyal, AP (ESIS Disp.)'],
    Nellore: [
      'Gudur, AP (ESIS Disp.)',
      'A.K.Nagar, AP (ESIS Disp.)',
      'Chinna Padugupadu, AP (ESIS Disp.)',
      'Nawabpet, AP (ESIS Disp.)',
      'Sullurpet, AP (ESIS Disp.)',
      'Tada, AP (ESIS Disp.)',
      'A.K.Nagar, AP (ESIS Disp.)',
      'Gudur, AP (ESIS Disp.)',
      'Nawabpet, AP (ESIS Disp.)',
      'Chinna Padugupadu, AP (ESIS Disp.)',
      'Sullurpet, AP (ESIS Disp.)',
      'Tada, AP (ESIS Disp.)',
      'Chillakuru, AP (ESIS Disp.)',
      'Muthukuru, AP (ESIS Disp.)',
      'Naidupeta, AP (ESIS Disp.)',
    ],
    Prakasam: [
      'Chirala, AP (ESIS Disp.)',
      'Macherla, AP (ESIS Disp.)',
      'Markapuram, AP (ESIS Disp.)',
      'Chirala, AP (ESIS Disp.)',
      'Markapuram, AP (ESIS Disp.)',
      'DCBO - Ongole',
      'Martur, AP (ESIS Disp.)',
      'Ongole, AP (ESIS Disp.)',
    ],
    'Sri Sathya Sai': ['Hindupur, AP (ESIS Disp.)', 'Kotnur, AP (ESIS Disp.)'],
    Srikakulam: ['Pydibhimavaram, AP (ESIS Disp.)', 'DCBO - Srikakulum'],
    Tirupati: [
      'Renigunta, AP (ESIS Disp.)',
      'Srikalahasti, AP (ESIS Disp.)',
      'Tirupathi, AP (ESIS Disp.)',
      'DCBO-Tirupathi',
    ],
    Vishakapatnam: [
      'Chittivalasa, AP (ESIS Disp.)',
      'Ramnagar, AP (ESIS Disp.)',
      'Gajuwaka, AP (ESIS Disp.)',
      'Gopalapatnam, AP (ESIS Disp.)',
      'Gandhigram, AP (ESIS Disp.)',
      'Industrial Estate, AP (ESIS Disp.)',
      'Pedagantyada, AP (ESIS Disp.)',
      'Nellimarla, AP (ESIS Disp.)',
      'Vizianagaram, AP (ESIS Disp.)',
      'Kothavalasa, AP (ESIS Disp.)',
      'Kurmannapalem, AP (ESIS Disp.)',
      'Balayyasastri Layout, AP (ESIC DISP)',
      'Panthulugarimeda,AP (ESIC DISP)',
      'Srikakulam , AP (ESIC DISP)',
      'Rly Kodur, AP (ESIS Disp.)',
      'Proddutur, AP (ESIS Disp.)',
      'Yerraguntla, AP (ESIS Disp.)',
      'Chittivalasa, AP (ESIS Disp.)',
      'Gajuwaka, AP (ESIS Disp.)',
      'Gandhigram, AP (ESIS Disp.)',
      'Gopalapatnam, AP (ESIS Disp.)',
      'Kothavalasa, AP (ESIS Disp.)',
      'Nellimarla, AP (ESIS Disp.)',
      'Pedagantyada, AP (ESIS Disp.)',
      'Sreeramnagar, AP (ESIS Disp.)',
      'Vizianagaram, AP (ESIS Disp.)',
      'Atchutapuram, AP (ESIS Disp.)',
      'DCBO - Anakapalle',
    ],
    Vizianagaram: [
      'Sreeramnagar, AP (ESIS Disp.)',
      'Bobbili, AP (ESIS Disp.)',
      'Bobbili, AP (ESIS Disp.)',
    ],
    'West Godawari': [
      'Bhimavaram, AP (ESIS Disp.)',
      'Eluru, AP (ESIS Disp.)',
      'Kovvuru, AP (ESIS Disp.)',
      'Nidadavolu, AP (ESIS Disp.)',
      'Tadepalligudem, AP (ESIS Disp.)',
      'Vendra, AP (ESIS Disp.)',
      'Tanuku, AP (ESIS Disp.)',
      'Dowleswaram, AP (ESIS Disp.)',
      'Eluru, AP (ESIS Disp.)',
      'Kadiyam, AP (ESIS Disp.)',
      'Kakinada, AP (ESIS Disp.)',
      'Kovvuru, AP (ESIS Disp.)',
      'Nidadavolu, AP (ESIS Disp.)',
      'Lalacheruvu, AP (ESIS Disp.)',
      'Innispeta, AP (ESIS Disp.)',
      'Seethampeta, AP (ESIS Disp.)',
      'Samalkot, AP (ESIS Disp.)',
      'Sarpavaram, AP (ESIS Disp.)',
      'Tadepalligudem, AP (ESIS Disp.)',
      'Tanuku, AP (ESIS Disp.)',
      'Vendra, AP (ESIS Disp.)',
      'Bhimavaram, AP (ESIS Disp.)',
    ],
  },
  'Arunachal Pradesh': {
    Anjaw: [],
    Changlang: [],
    'Dibang Valley': [],
    'East Kameng': [],
    'East Siang': [],
    'Kra Daadi': [],
    'Kurung Kumey': [],
    Lohit: [],
    Longding: [],
    'Lower Dibang Valley': [],
    'Lower Siang': [],
    'Lower Subansiri': [],
    Namsai: [],
    'Papum Pare': [],
    Siang: [],
    Tawang: [],
    Tirap: [],
    'Upper Siang': [],
    'Upper Subansiri': [],
    'West Kameng': [],
    'West Siang': [],
  },
  Assam: {
    Anjaw: [],
    Changlang: [],
    'Dibang Valley': [],
    'East Kameng': [],
    'East Siang': [],
    'Kra Daadi': [],
    'Kurung Kumey': [],
    Lohit: [],
    Longding: [],
    'Lower Dibang Valley': [],
    'Lower Siang': [],
    'Lower Subansiri': [],
    Namsai: [],
    'Papum Pare': [],
    Golaghat: ['Numaligarh, AS (ESIS Disp.)'],
    Hailakandi: [],
    Hojai: [],
    Jorhat: ['Jorhat, AS (ESIS Disp.)'],
    Kamrup: ['Amingaon, AS (ESIS Disp.)'],
    'Kamrup Metropolitan': [
      'Noonmati, AS (ESIS Disp.)',
      'Jalukbari, AS (ESIS Disp.)',
      'Lokhra, AS (ESIS Disp.)',
      'DIMS, Assam (ESIS DIMS)',
      'Jayanagar, AS (ESIC Hosp.)',
      'Guwahati, AS (ESIS Diag.)',
      'Guwahati Refinery, AS (ESIS Disp.)',
      'Uzanbazar, AS (ESIS Disp.)',
      'Kalapahar, AS (ESIS Disp.)',
      'Dispur, AS (ESIS Disp.)',
      'Khanapara, AS (ESIS Disp.)',
      'Narengi, AS (ESIS Disp.)',
    ],
    'Karbi Anglong': [],
  },
  Bihar: {
    Araria: [],
    Arwal: [],
    Aurangabad: [
      'D 4 Chikalthana, Aurangabad, MH (ESIS Disp.)',
      'D 3 HUDCO, Aurangabad, MH (ESIS Disp.)',
      'D 2 Aurangabad, MH (ESIS Disp.)',
      'D 1 Waluj, Aurangabad, MH (ESIS Disp.)',
      'Digha, Bihar (ESIS Disp.)',
      'Hathidah, BH (ESIS Disp.)',
      'Jamal Road, BH (ESIS Disp.)',
      'Patliputra, Bihar (ESIS Disp.)',
    ],
    Banka: [],
    Begusarai: [
      'Harpur, Bihar (ESIS Disp.)',
      'Shambhu Prasad, BH (ESIS Disp.)',
      'DCBO - Begusarai',
    ],
    Bhagalpur: [
      'Bhagalpur, Bihar (ESIS Disp.)',
      'Gurumani Sadan, BH (ESIS Disp.)',
      'Ma Medica, BH (ESIS Disp.)',
      'DCBO - Bhagalpur',
    ],
    Bhojpur: ['DCBO - Ara'],
    Buxar: ['Dumraon, Bihar (ESIS Disp.)'],
    Darbhanga: [
      'Darbhanga, Bihar (ESIS Disp.)',
      'DCBO-Darbhanga, BH (ESIC DCBO.)',
    ],
    Gaya: [
      'Gaya, Bihar (ESIS Disp.)',
      'Katihar, Bihar (ESIS Disp.)',
      'Kanakarbagh, Bihar (ESIS Disp.)',
      'Phulwarisharif, Bihar (ESIS Disp.)',
      'Ranipur, Bihar (ESIS Disp.)',
      'New Area, BH (ESIS Disp.)',
      'DCBO - Gaya',
    ],
    Gopalganj: [
      'Gaya, Bihar (ESIS Disp.)',
      'Katihar, Bihar (ESIS Disp.)',
      'Kanakarbagh, Bihar (ESIS Disp.)',
      'Phulwarisharif, Bihar (ESIS Disp.)',
      'Ranipur, Bihar (ESIS Disp.)',
      'New Area, BH (ESIS Disp.)',
      'DCBO - Gaya',
    ],
    Jamui: [
      'Gaya, Bihar (ESIS Disp.)',
      'Katihar, Bihar (ESIS Disp.)',
      'Kanakarbagh, Bihar (ESIS Disp.)',
      'Phulwarisharif, Bihar (ESIS Disp.)',
      'Ranipur, Bihar (ESIS Disp.)',
      'New Area, BH (ESIS Disp.)',
      'DCBO - Gaya',
    ],
    Jehanabad: [],
    Kaimur: [],
    Katihar: [
      'Aragara Chowk, BH (ESIS Disp.)',
      'DCBO-Katihar, BH (ESIC DCBO.)',
    ],
    Khagaria: [],
    Kishanganj: [],
    Lakhisarai: [],
    Madhepura: [],
    Madhubani: [],
    Munger: ['Munger, Bihar (ESIS Disp.)', 'Shouji Ghat, BH (ESIS Disp.)'],
    Muzaffarpur: [
      'Kalambagh Chowk, BH (ESIS Disp.)',
      'DCBO-Muzaffarpur, BH (ESIC DCBO.)',
    ],
    Nalanda: [
      'Biharsharif, Bihar (ESIS Disp.)',
      'Bihata, Bihar (ESIS Disp.)',
      'Mogal Kuan, BH (ESIS Disp.)',
    ],
    Nawada: [],
    'Pashchim Champaran': [],
    Patna: [
      'Phulwarisharif, BH (ESIS Disp.)',
      'ESI Dispensary - Shambhu Prasad, Bihar',
      'ESI Dispensary - Gurumani Sadan, Bihar',
      'ESI Dispensary - Ma Medica, Bihar',
      'ESI Dispensary - Mogal Kuan, Bihar',
      'ESI Dispensary - New Area, Bihar',
      'ESI Dispensary - Rana Pratap Colony, Bihar',
      'ESI Dispensary - Aragara Chowk, Bihar',
      'Hathidah, BH (ESIS Disp.)',
      'ESI Dispensary - Kalambagh Chowk, Bihar',
      'ESI Dispensary - Shouji Ghat, Bihar',
      'ESI Dispensary - Mahabir Nagar, Bihar',
      'ESI Dispensary - Bata Ganj Digha, Bihar',
      'ESI Dispensary - Bata Factory Campus, Bihar',
      'Jamal Road, BH (ESIS Disp.)',
      'ESI Dispensary - Kankarbagh, Bihar',
      'ESI Dispensary - Patliputra, Bihar',
      'ESI Dispensary - Nasariganj, Bihar',
      'ESI Dispensary - Phulwarisharif, Bihar',
      'ESI Dispensary - Ranipur Khirki, Bihar',
      'ESI Dispensary - Bajari, Bihar',
      'ESI Dispensary -Muktapur, Bihar',
      'ESI Dispensary - Hajipur Vaishali, Bihar',
      'Bihta, BH (ESIS Disp.)',
      'Chavakkad, KL (ESIS Disp.)',
      'Bata Ganj Digha, BH (ESIS Disp.)',
      'Kankarbagh, BH (ESIS Disp.)',
      'Ranipur Khirki, BH (ESIS Disp.)',
      'DCBO - Patna',
    ],
    'Purba Champaran': [],
    Purnia: [],
    Rohtas: [
      'Banjari, Bihar (ESIS Dip.)',
      'Bajari, BH (ESIS Disp.)',
      'DCBO-Dalmianagar, BH (ESIC DCBO.)',
    ],
    Saharsa: [],
    Samastipur: [
      'Samastipur, Bihar (ESIS Disp.)',
      'Muktapur, BH (ESIS Disp.)',
      'DCBO-Samastipur, BH (ESIC DCBO.)',
    ],
    Saran: [],
    Sheikhpura: [],
    Sheohar: [],
    Sitamarhi: [],
    Siwan: [],
    Supaul: [],
    Vaishali: ['Hajipur Vaishali, BH (ESIS Disp.)', 'DCBO - Hajipur'],
  },
  Chandigarh: {
    Chandigarh: [
      'Sec 29 Chandigarh (ESIS Disp.)',
      'Sector 23, Ch (ESIS Disp.)',
    ],
  },
  Chhattisgarh: {
    Balod: [],
    'Baloda Bazar': [
      'Balodabazar,CT (ESIS Disp.)',
      'Bhathapara, Baloda Bazar, CT (ESIS Disp.)',
      'Hirmi- Rawan, CT (ESIS Disp.)',
      'Baloda Bazar,CT (ESIS Disp.)',
    ],
    Balrampur: [],
    Bastar: ['DCBO-Jagdalpur, CT (ESIC DCBO)'],
    Bemetara: [],
    Bijapur: [],
    Bilaspur: [
      'Bilaspur, CT (ESIS Disp.)',
      'Belha, Bilaspur, CT (ESIS disp.)',
      'Sipat, Bilaspur, CT (ESIS Disp.)',
      'Sipat,Rajim,CT (ESIS Disp.)',
    ],
    Dantewada: [],
    Dhamtari: ['Dhamtari,CT (ESIS Disp.)', 'Dhamtari, CT (ESIS Disp.)'],
    Durg: [
      'Hathkhoj, CT (ESIS Disp.)',
      'Kumhari, CT (ESIS Disp.)',
      'Bhilai Suplea, CT (ESIS Disp.)',
      'Nandini Road, CT (ESIS Disp.)',
      'Rasmada,CT (ESIS Disp.)',
      'Durg,CT (ESIS Disp.)',
      'Jamul,CT (ESIS Disp.)',
      'Rasmara, CT (ESIS Disp.)',
      'Malviya Nagar, Durg, CT (ESIS Disp.)',
      'North Vasundara Nagar, Bhilai, Durg, CT (ESIS Disp.)',
      'Ganesh Nagar, Bhilai, Durg, CT (ESIS Disp.)',
      'Jamul, Durg, CT (ESIS Disp.)',
      'Durg,CT (ESIS Disp.)',
    ],
    Gariaband: ['Nawapara Rajim,CT (ESIS Disp.)', 'Rajim,CT (ESIS Disp.)'],
    'Gaurella-Pendra-Marwahi': [],
    'Janjgir-Champa': [
      'Champa, CT (ESIS Disp.)',
      'Dabhra, Jangir-Champa, CT (ESIS Disp.)',
      'Akaltara, Jangir Champa, CT (ESIS Disp.)',
      'Chandrapur-Sarangarh, CT (ESIS Disp.)',
      'Akaltara, CT (ESIS Disp.)',
      'Dabhra,CT (ESIS Disp.)',
    ],
    Jashpur: [],
    Kabirdham: [],
    Kanker: [],
    Kondagaon: [],
    Korba: [
      'Korba, CT (ESIS Disp.)',
      'Balco Nagar,CT (ESIS Disp.)',
      'Darrijamnipali,CT (ESIS Disp.)',
      'Balco, CT (ESIS Disp.)',
      'Jamnipali, Korba, CT (ESIS Disp.)',
      'Patadi, Korba, CT (ESIS Disp.)',
      'Dipka, CT (ESIS Disp.)',
      'Jamnipali,CT (ESIS Disp.)',
      'Urga Patadi ,CT (ESIS Disp.)',
    ],
    Koriya: [
      'Korba, CT (ESIS Disp.)',
      'Balco Nagar,CT (ESIS Disp.)',
      'Darrijamnipali,CT (ESIS Disp.)',
      'Balco, CT (ESIS Disp.)',
      'Jamnipali, Korba, CT (ESIS Disp.)',
      'Patadi, Korba, CT (ESIS Disp.)',
      'Dipka, CT (ESIS Disp.)',
      'Jamnipali,CT (ESIS Disp.)',
      'Urga Patadi ,CT (ESIS Disp.)',
    ],
    Mahasamund: [],
    Mungeli: [],
    Narayanpur: [],
    Raigarh: [
      'Raigarh, CT (ESIS Disp.)',
      'Patrapali, CT (ESIS Disp.)',
      'Taraimal, CT (ESIS Disp.)',
      'Jamgaon, Raigarh, CT (ESIS Disp.)',
      'Bhupdeopur, CT (ESIS Disp.)',
      'Tamnar, CT (ESIS Disp.)',
      'Jamgaon,CT (ESIS Disp.)',
    ],
    Raipur: [
      'Fafadih , CT (ESIS Disp.)',
      'Birgaon, CT (ESIS Disp.)',
      'Kabir Nagar disp, CT (ESIS Disp.)',
      'Choubey Colony,Raipur (CG), CT (ESIS Disp.)',
      'Mandir Hasud, CT (ESIS Disp.)',
      'Baikunth (Tilda),CT (ESIS Disp.)',
      'DIMS, Chhattisgarh (ESIS DIMS)',
      'Tilda, CT (ESIS Disp.)',
      'Mandir Hasud, CT (ESIS Disp.)',
      'Choubey Colony,Raipur (CG), CT (ESIS Disp.)',
      'Rajim Navapara, Raipur, CT (ESIS Disp.)',
      'Sejbahar-Dunda, CT (ESIS Disp.)',
      'Siltara, CT (ESIS Disp.)',
    ],
    Rajnandgaon: [
      'Rajnandgaon, CT (ESIS Disp.)',
      'Tedesara,CT (ESIS Disp.)',
      'Tedesara Rajnandgaon, CT (ESIS Disp.)',
      'Tumbibod, Rajnandgaon, CT (ESIS Disp.)',
      'Tumdibod,CT (ESIS Disp.)',
      'DCBO - Rajnandgaon',
    ],
    Sukma: [
      'Rajnandgaon, CT (ESIS Disp.)',
      'Tedesara,CT (ESIS Disp.)',
      'Tedesara Rajnandgaon, CT (ESIS Disp.)',
      'Tumbibod, Rajnandgaon, CT (ESIS Disp.)',
      'Tumdibod,CT (ESIS Disp.)',
      'DCBO - Rajnandgaon',
    ],
    Surajpur: [],
    Surguja: [],
  },
  'Dadra and Nagar Haveli': {
    'Dadra and Nagar Haveli': [],
  },
  'Daman and Diu': {
    'Dadra and Nagar Haveli': [],
  },
  Delhi: {
    'Dadra and Nagar Haveli': [],
  },
  Goa: {
    'Dadra and Nagar Haveli': [],
  },
  Gujarat: {
    'Dadra and Nagar Haveli': [],
  },
  Haryana: {
    Ambala: [
      'Old Civil Hosp. Bldg, Ambala, HR (ESIS Disp.)',
      'Ambala Cantt, HR (ESIS Disp.)',
      'Dhulkot, Palika Vihar, HR (ESIS Disp.)',
      'Naraingarh, HR (ESIS Disp)',
    ],
    Bhiwani: [
      'D 1 Mela Ground, Bhiwani, HR (ESIS Disp.)',
      'D 2 Mela Ground, Bhiwani, HR (ESIS Disp.)',
      'D 3 Ind. Area, Bhiwani, HR (ESIS Disp.)',
      'Khanak, Bhiwani, HR (ESIS Disp.)',
    ],
    'Charkhi Dadri': [],
    Faridabad: [],
    Fatehabad: [],
    Gurgaon: [
      'D 2 Udyogvihar, Gurgaon, HR (ESIS Disp.)',
      'D 1 Nr Sharma Rest., Gurgaon, HR (ESIS Disp.)',
      'D 3 Nr Sharma Rest., Gurgaon, HR (ESIS Disp.)',
      'Manesar, HR (ESIS Disp.)',
      'Sohna, HR (ESIS Disp.)',
      'Basai Road,Gurgaon , HR (ESIS Disp.)',
      'Binola, HR (ESIS Disp.)',
      'Daultabad,Gurgaon , HR (ESIS Disp.)',
      'New Dharuhera, Gurgaon, HR (ESIS Disp.)',
      'Kanahi, HR (ESIS Disp.)',
      'Islampur, HR (ESIS Disp.)',
      'Kherkidaula, Gurgaon, HR (ESIS Disp.)',
      'New Manesar, Gurgaon, HR (ESIS Disp.)',
      'Narnaul, Gurgaon, HR (ESIS Disp.)',
      'Nathupur, Gurgaon, HR (ESIS Disp.)',
      'Palam Vihar, Gurgaon, HR (ESIS Disp.)',
      'Sector-37, Gurgaon, HR (ESIS Disp.)',
    ],
    Hissar: [
      'Hisar Road, Hansi, HR (ESIS Disp.)',
      'D 1 DCM Textile Road, HR (ESIS Disp.)',
      'D 2 DCM Textile Road, HR (ESIS Disp.)',
      'Mayer, HR (ESIS Disp.)',
      'Jindal Chowk, HR (ESIS Disp.)',
    ],
    Jhajjar: [
      'ESIS Disp. 1, Sec-6 Bahadurgarh, HR (ESIS Disp.)',
      'ESIS Disp. 3,badli Road Bahadurgarh, HR (ESIS Disp.)',
      'ESIS Disp. 2, Netaji Nagar, Linepaar, Bahdurgarh,HR',
      'Netaji Ngar,Bahadurgarh, HR (ESIS Disp.)',
      'DCBO - Bahadurgarh',
      'Jhajjar, HR (ESIC Disp.)',
      'Jhajjar, HR (ESIS)',
    ],
    Jind: ['Urban Estate, HR (ESIS Disp.)'],
    Kaithal: ['Urban Estate, HR (ESIS Disp.)'],
    Karnal: ['Urban Estate, HR (ESIS Disp.)'],
    Kurukshetra: ['Kurukshetra, HR (ESIS Disp.)'],
    Mahendragarh: [],
    Mewat: [],
    Nuh: [],
    Palwal: ['Prithla, Palwal, HR (ESIS Disp.)'],
    Panchkula: [
      'Panchkula, HR (ESIS Disp.)',
      'Pinjore Garden, HR (ESIS Disp.)',
    ],
    Panipat: [
      'D 1 Panipat, HR (ESIS Disp.)',
      'D 2 Model Town, Panipat, HR (ESIS Disp.)',
      'Samalkha, HR (ESIS Disp.)',
      'ESI Disp. 3, Panipat, HR (ESIS Disp.)',
    ],
    Rewari: [
      'Bawal, Rewari, HR (ESIS Disp.)',
      'Dharuhera, HR (ESIS Disp.)',
      'Rewari, HR (ESIS Disp.)',
      'Bawal, Rewari, HR (ESIS Disp.)',
      'No. 2,Rewari, HR (ESIS Disp.)',
    ],
    Rohtak: ['Rohtak, HR (ESIS Disp.)', 'Sampla, HR (ESIS Disp.)'],
    Sirsa: ['Sirsa, HR (ESIS Disp.)'],
    Sonipat: [
      'Rai Sonipat, HR (ESIS Disp.)',
      'Bahalgarh, Sonipat, HR (ESIS Disp.)',
      'Kundali, Sonipat, HR (ESIS Disp.)',
      'Murthal, Sonipat, HR (ESIS Disp.)',
      'Sonipat, HR (ESIS Disp.)',
      'Barahi,Sonepat Faridabad, HR (ESIS Disp.)',
      'Gohana, HR (ESIS Disp.)',
    ],
    'Yamuna Nagar': [
      'D 1 & 2 Jagadhari, HR (ESIS Disp.)',
      'D 3 Jagadhari, HR (ESIS Disp.)',
      'ESI Dispensary No.7, Saini Majra, Damla',
      'D 5 YNR, HR (ESIS Disp.)',
      'ESI Dispensary No-6, Shadipur, Yamuna Nagar',
      'No.8, Jagadhri, HR (ESIS Disp.)',
      'No.9, Jagadhri, HR (ESIS Disp.)',
      'Dispensary No.-4 Yamuna Nagar, HR(ESIS Disp)',
    ],
  },
  'Himachal Pradesh': {
    Bilaspur: ['Bilaspur, CT (ESIS Disp.)', 'Panjgane, HP (ESIS Disp.)'],
    Chamba: ['PHC Banikhet, HP (ESIS Disp.)'],
    Hamirpur: ['CH Tauni Devi, HP (ESIS Disp.)'],
    Kangra: ['CH Tauni Devi, HP (ESIS Disp.)'],
    Kinnaur: ['CH Tauni Devi, HP (ESIS Disp.)'],
    Kulu: ['PHC Bran, HP (ESIS Disp.)'],
    'Lahaul and Spiti': ['PHC Tabo, HP (ESIS Disp.)'],
    Mandi: ['DCBO - Mandi'],
    Shimla: [
      'Deen Dayal Upadhyaya, HP (ESIS Disp.)',
      'Shoghi, HP (ESIS Disp.)',
    ],
    Sirmaur: [
      'Kalaamb, HP (ESIS Disp.)',
      'Patlian, HP (ESIS Disp.)',
      'Gondpur (Rampurghat), HP (ESIS Disp.)',
    ],
    Solan: [
      'Baddi, HP (ESIS Disp.)',
      'Barotiwala, HP (ESIS Disp.)',
      'Jabli, HP (ESIS Disp.)',
      'Nalagarh, HP (ESIS Disp.)',
      'Chambaghat Solan, HP (ESIS Disp.)',
      'Kasauli, HP (ESIS Disp.)',
      'Darlaghat, HP (ESIS Disp.)',
    ],
    Una: [
      'Mehatpur, HP (ESIS Disp.)',
      'Tahliwal, HP (ESIS Disp.)',
      'Gagret, HP (ESIS Disp.)',
    ],
  },
  'Jammu and Kashmir': {
    Anantnag: [],
    Badgam: [],
    Bandipore: [],
    Baramula: ['Madiwala Dispensary'],
    Doda: [],
    Ganderbal: [],
    Jammu: [
      'Talab Tillo ,JK (ESIS Disp.)',
      'Bari Brahamana, JK (ESIS Disp.)',
      'Digiana, JK (ESIS Disp.)',
    ],
    Kargil: [],
    Kathua: ['Kathua, JK (ESIC Disp.)', 'DCBO - Kathua'],
    Kishtwar: [],
    Kulgam: [],
    Kupwara: [],
    Leh: [],
    Poonch: [],
    Pulwama: [],
    Rajauri: [],
    Ramban: [],
    Reasi: ['DCBO - Katra'],
    Samba: ['DCBO - Samba'],
    Shopian: [],
    Srinagar: [
      'Srinagar, JK (ESIS Disp.)',
      'Bagh-E-Ali Mardan Khan, JK (ESIS Disp.)',
      'Rangreth, JK (ESIS Disp.)',
      'Zainakote, JK (ESIS Disp.)',
      'DCBO - Srinagar',
    ],
    Udhampur: ['DCBO - Udhampur'],
  },
  Jharkhand: {
    Bokaro: ['Sivandih Bokaro, JH (ESIS Disp.)'],
    Chatra: [],
    Deoghar: ['Madhupur, JH (ESIS Disp.)', 'Jashidih, JH (ESIS Disp.)'],
    Dhanbad: [
      'Gobindpur, JH (ESIS Disp.)',
      'Dhanbad Jora Phatak, JH (ESIS Disp.)',
      'Kumardhub, JH (ESIS Disp.)',
      'Maithon MUGMA, JH (ESIS Disp.)',
      'Nirsa, JH (ESIS Disp.)',
      'Bhadaninagar, JH (ESIS Disp.)',
    ],
    Dumka: [],
    Garhwa: [],
    Giridih: ['Makatpur Giridih, JH (ESIS Disp.)'],
    Godda: ['DCBO - Godda, JH (ESIC DCBO)'],
    Gumla: [],
    Hazaribagh: [],
    Jamtara: [],
    Khunti: ['DCBO - Khunti, JH (ESIC DCBO)'],
    Koderma: ['Jhumri Talaiya, JH (ESIS Disp.)'],
    Latehar: [],
    Lohardaga: [],
    Pakaur: [],
    Palamu: ['DCBO - Daltonganj, JH (ESIC DCBO)'],
    'Pashchimi Singhbhum': [],
    'Purbi Singhbhum': [
      'Jugsalai, JH (ESIS Disp.)',
      'Sakchi, JH (ESIS Disp.)',
      'Jawahar Nagar Maango, JH (ESIS Disp.)',
      'DCBO-Purbi Singhbhum',
    ],
    Ramgarh: ['Ram Garh, JH (ESIS Disp.)'],
    Ranchi: [
      'D 1 Junagadh, Rajkot, GJ (ESIS Disp.)',
      'Dhurwa, JH (ESIS Disp.)',
      'Kokar, JH (ESIS Disp.)',
      'Tati Silway, JH (ESIS Disp.)',
      'Tupu Dana, JH (ESIS Disp.)',
      'Ormanjhi, JH (ESIS Disp.)',
    ],
    Sahibganj: ['DCBO - Sahibganj, JH (ESIC DCBO)'],
    'Seraikela-Kharsawan': [
      'Adityapur, JH (ESIS Disp.)',
      'Saraikela Jamharia, JH (ESIS Disp.)',
      'Kandra, JH (ESIS Disp.)',
    ],
    Simdega: [],
  },
  Karnataka: {
    Bagalkot: [
      'Bagalkot, KA (ESIS Disp.)',
      'Banahatti, KA (ESIS Disp.)',
      'DCBO - Bagalkote',
    ],
    Bangalore: [
      'Wilson Garden, KA (ESIS Disp.)',
      'Attibelle, KA (ESIS Disp.)',
      'Banashankari, KA (ESIS Disp.)',
      'Basavanagudi, KA (ESIS Disp.)',
      'Binnypet, KA (ESIS Disp.)',
      'Bommanahalli, KA (ESIS Disp.)',
      'Bommasandra, KA (ESIS Disp.)',
      'Channapatna, KA (ESIS Disp.)',
      'Cottonpet, KA (ESIS Disp.)',
      'Dasarahalli, KA (ESIS Disp.)',
      'Dodaballapura, KA (ESIS Disp.)',
      'Dyavasandra, KA (ESIS Disp.)',
      'Frazer Town, KA (ESIS Disp.)',
      'Hanumantha Nagar, KA (ESIS Disp.)',
      'Hoskote, KA (ESIS Disp.)',
      'Jalahalli, KA (ESIS Disp.)',
      'Jayanagar, KA (ESIS Disp.)',
      'Jigani, KA (ESIS Disp.)',
      'K R Puram I, KA (ESIS Disp.)',
      'Mysore road, KA (ESIS Disp.)',
      'Kengeri, KA (ESIS Disp.)',
      'Konanakunte, KA (ESIS Disp.)',
      'Magadi, KA (ESIS Disp.)',
      'Marathahalli, KA (ESIS Disp.)',
      'K R Puram II, KA (ESIS Disp.)',
      'Nelamangala, KA (ESIS Disp.)',
      'Peenya, KA (ESIS Disp.)',
      'R.T.Nagar, KA (ESIS Disp.)',
      'Rajajinagar II, KA (ESIS Disp.)',
      'Rajajinagar I, KA (ESIS Disp.)',
      'Russel Market, KA (ESIS Disp.)',
      'Sheshadripuram, KA (ESIS Disp.)',
      'Singasandra, KA (ESIS Disp.)',
      'Sriramapuram, KA (ESIS Disp.)',
      'Subramanyapura, KA (ESIS Disp.)',
      'Ulsoor, KA (ESIS Disp.)',
      'Vijayanagara, KA (ESIS Disp.)',
      'Vishwaneedam, KA (ESIS Disp.)',
      'Viveknagar, KA (ESIS Disp.)',
      'White field dispensary, KA (ESIS Disp.)',
      'Yelahanka, KA (ESIS Disp.)',
      'Yeshwanthapura, KA (ESIS Disp.)',
      'K R Puram II, KA (ESIS Disp.)',
      'Mysore road, KA (ESIS Disp.)',
      'K R Puram I, KA (ESIS Disp.)',
      'Rajajinagar I, KA (ESIS Disp.)',
      'Rajajinagar II, KA (ESIS Disp.)',
      'Wilson Garden, KA (ESIS Disp.)',
      'JINDAL Dispensary',
      'White field, KA (ESIS Disp.)',
      'ESID Mallur, KA (ESIS Disp.)',
      'Ammasandra Cement Factory, KA (ESIS Disp.)',
      'Jindal Factory Premises, KA (ESIS Disp.)',
      'Basavanagudi, KA (ESIS DC)',
      'Madanayakanahalli, KA (ESIS Disp.)',
      'RML College, Gottigere, KN (ESIS Disp.)',
      'Laggere, KA (ESIS Disp.)',
      'Devanahall, KA (ESIS Disp.)',
      'DCBO - Biharsharif',
    ],
    'Bangalore Rural': ['BELHospital, KA (ESIS Disp.)'],
    Belgaum: ['BELHospital, KA (ESIS Disp.)'],
    Bellary: [
      'Bellary, KA (ESIS Disp.)',
      'T.B.Dam, KA (ESIS Disp.)',
      'EUD - Toranagallu',
    ],
    Bidar: ['DCBO - Bidar, KA (ESIC DCBO)'],
    Chamarajnagar: ['DCBO - Chamarajanagar'],
    Chickmagloor: ['DCBO- Chikkamagaluru'],
    Chikballapur: ['DCBO-Chikballapur'],
    Chitradurga: [
      'Chitradurga, KA (ESIS Disp.)',
      'Chitradurga, KA (ESIS Disp.)',
    ],
    'Dakshina Kannada': [
      'Karangalpadi, KA (ESIS Disp.)',
      'Kulshekar, KA (ESIS Disp.)',
      'Margan\u2019s, KA (ESIS Disp.)',
      'Panambur, KA (ESIS Disp.)',
      'Puttur, KA (ESIS Disp.)',
      'Puttur, KA (ESIS Disp.)',
    ],
    Davanagere: [
      'Karangalpadi, KA (ESIS Disp.)',
      'Kulshekar, KA (ESIS Disp.)',
      'Margan\u2019s, KA (ESIS Disp.)',
      'Panambur, KA (ESIS Disp.)',
      'Puttur, KA (ESIS Disp.)',
      'Puttur, KA (ESIS Disp.)',
    ],
    Dharwad: [
      'Dharwad, KA (ESIS Disp.)',
      'Belur, KA (ESIS Disp.)',
      'Tarihal, KA (ESIS Disp.)',
      'Hubli-I, KA (ESIS Disp.)',
      'Varur Dispensary (ESIS Disp.)',
      'Gokul Road, Industrial Area, Hubli, KN (ESIS Disp.)',
    ],
    Gadag: ['Gadag, KA (ESIS Disp.)', 'Hulikote, KA (ESIS Disp.)'],
    Hassan: ['Hassan, KA (ESIS Disp.)'],
    Haveri: ['Hassan, KA (ESIS Disp.)'],
    KALBURGI: [
      'M.S.K.Mills, Gulbarga, KA (ESIS Disp.)',
      'Sedam, KA (ESIS Disp.)',
      'Shahabad Town, KA (ESIS Disp.)',
      'Malkhed, KA (ESIS Disp.)',
      'Wadi, KA (ESIS Disp.)',
    ],
    Kodagu: ['DCBO - Kodagu'],
    Kolar: ['Robertsonpet, KA (ESIS Disp.)'],
    Koppal: ['17 MIG 2, KHB Colony, Koppal, KN (ESIS Disp.)'],
    Mandya: [
      'Maddur, KA (ESIS Disp.)',
      'Belagola, KA (ESIS Disp.)',
      'Mandya, KA (ESIS Disp.)',
      'Belagola, KA (ESIS Disp.)',
      'Belagola, KA (ESIS Disp.)',
    ],
    Mysore: [
      'Belawadi, KA (ESIS Disp.)',
      'Brindavan, KA (ESIS Disp.)',
      'Hunsur, KA (ESIS Disp.)',
      'Mysore Central, KA (ESIS Disp.)',
      'Mysore South, KA (ESIS Disp.)',
      'N.R.Mohalla, KA (ESIS Disp.)',
      'V.V.Puram, KA (ESIS Disp.)',
      'Nanjangud, KA (ESIS Disp.)',
      'T.Narasipura, KA (ESIS Disp.)',
    ],
    Raichur: ['Raichur, KA (ESIS Disp.)'],
    Ramanagar: ['Raichur, KA (ESIS Disp.)'],
    Shimoga: [
      'Shimoga, KA (ESIS Disp.)',
      'Bhadravathi, KA (ESIS Disp.)',
      'MACHENAHALLI, KA (ESIS Disp.)',
      'NR Road, Shimoga, KN (ESIS Disp.)',
      'Vinobhanagar, Shimoga, KN (ESIS Disp.)',
    ],
    Tumkur: [
      'Kunigal, KA (ESIS Disp.)',
      'Tumkur, KA (ESIS Disp.)',
      'Kunigal, KA (ESIS Disp.)',
      'Tumkur, KA (ESIS Disp.)',
      'Tiptur, KA (ESIS Disp.)',
    ],
    Udupi: [
      'Manipal, KA (ESIS Disp.)',
      'Karkala, KA (ESIS Disp.)',
      'Kundapura, KA (ESIS Disp.)',
      'Udupi, KA (ESIS Disp.)',
    ],
    'Uttara Kannada': ['Dandeli,KA(ESIS Disp.)', 'DCBO - Karwar'],
    Vijayapura: ['Bijapur, KA (ESIS Disp.)'],
    Yadagiri: ['DCBO - Yadgiri, KA (ESIC DCBO)'],
  },
  Kerala: {
    Alappuzha: [
      'Beach Ward, KL (ESIS Disp.)',
      'Factory Ward, KL (ESIS Disp.)',
      'Ezhupunna, KL (ESIS Disp.)',
      'Kayamkulam (ESIS Disp.)',
      'Aroor, KL (ESIS Disp.)',
      'Chengannur, KL (ESIS Disp.)',
      'Cherthala, KL (ESIS Disp.)',
      'Pathiyoor, KL (ESIS Disp.)',
      'Mannar, KL (ESIS Disp.)',
      'Muhamma, KL (ESIS Disp.)',
      'Karimulakkal, KL (ESIS Disp.)',
      'Palamel, KL (ESIS Disp.)',
      'Pathirappally, KL (ESIS Disp.)',
      'Beach Ward, KL (ESIS Disp.)',
      'Cherthala, KL (ESIS Disp.)',
      'Chengannur, KL (ESIS Disp.)',
      'Ezhupunna, KL (ESIS Disp.)',
      'Factory Ward, KL (ESIS Disp.)',
      'Karimughal, KL (ESIS Disp.)',
      'ESI Dispensary Kayankulam',
      'Pathiyoor, KL (ESIS Disp.)',
      'Mannar, KL (ESIS Disp.)',
      'Mavelikkara, KL (ESIS Disp.)',
      'Muhamma, KL (ESIS Disp.)',
      'Palamel, KL (ESIS Disp.)',
      'Pathirappally, KL (ESIS Disp.)',
    ],
    Ernakulam: [
      'Perumbavoor, KL (ESIS Disp.)',
      'Aluva No.1, KL (ESIS Disp.)',
      'Aluva No.2, KL (ESIS Disp.)',
      'Angamaly, KL (ESIS Disp.)',
      'Binanipuram, KL (ESIS Disp.)',
      'Athani, KL (ESIS Disp.)',
      'Edappally, KL (ESIS Disp.)',
      'Ernakulam, KL (ESIS Disp.)',
      'Thoppumpady, KL (ESIS Disp.)',
      'Kalamasserry, KL (ESIS Disp.)',
      'Karimughal, KL (ESIS Disp.)',
      'Udyogomandal, KL (ESIS Disp.)',
      'CSEZ Kakkanad, KL (ESIS Disp.)',
      'Fort Kochi, KL (ESIS Disp.)',
      'Koonammavu, KL (ESIS Disp.)',
      'N.Vazhakulam, KL (ESIS Disp.)',
      'Moovattupuzha, KL (ESIS Disp.)',
      'N.Paravoor, KL (ESIS Disp.)',
      'Njarakkal, KL (ESIS Disp.)',
      'Tripunithura, KL (ESIS Disp.)',
      'Aluva No.1, KL (ESIS Disp.)',
      'Aluva No.2, KL (ESIS Disp.)',
      'Angamaly, KL (ESIS Disp.)',
      'Athani, KL (ESIS Disp.)',
      'Binanipuram, KL (ESIS Disp.)',
      'Edappally, KL (ESIS Disp.)',
      'Eranjipalam, KL (ESIS Disp.)',
      'CSEZ Kakkanad, KL (ESIS Disp.)',
      'Kalamasserry, KL (ESIS Disp.)',
      'Karimulakkal, KL (ESIS Disp.)',
      'Koonammavu, KL (ESIS Disp.)',
      'Njarakkal, KL (ESIS Disp.)',
      'Thoppumpady, KL (ESIS Disp.)',
      'N.Paravoor, KL (ESIS Disp.)',
      'Fort Kochi, KL (ESIS Disp.)',
      'Perumbavoor, KL (ESIS Disp.)',
      'Ernakulam, KL (ESIS Disp.)',
      'Tripunithura, KL (ESIS Disp.)',
      'Udyogomandal, KL (ESIS Disp.)',
      'Bypore Cheruvannur, KL (ESIS Disp.)',
    ],
    Idukki: [
      'Thodupuzha, KL (ESIS Disp.)',
      'Attingal, KL (ESIS Disp.)',
      'Chakkorathukulam, KL (ESIS Disp.)',
      'Thodupuzha, KL (ESIS Disp.)',
      'Kazhakkuttam, KL (ESIS Disp.)',
      'Kilimanur, KL (ESIS Disp.)',
      'Kovalam, KL (ESIS Disp.)',
      'Neyyattinkara, KL (ESIS Disp.)',
      'Thiruvalla, KL (ESIS Disp.)',
      'Karamana, KL (ESIS Disp.)',
      'Madavoor, KL (ESIS Disp.)',
      'Navaikulam, KL (ESIS Disp.)',
      'Thaliparamba, KL (ESIS Disp.)',
      'Balaramapuram, KL (ESIS Disp.)',
      'DCBO - Munnar',
      'Kattappana, KL (ESIS Disp.)',
    ],
    Kannur: [
      'Azhikode, KL (ESIS Disp.)',
      'Kannur Kakkad, KL (ESIS Disp.)',
      'Kuthuparamba, KL (ESIS Disp.)',
      'Mele chowa, KL (ESIS Disp.)',
      'Mangattuparamba, KL (ESIS Disp.)',
      'Pappinissery, KL (ESIS Disp.)',
      'Payyannur, KL (ESIS Disp.)',
      'Thaliparamba, KL (ESIS Disp.)',
      'Valapattanam, KL (ESIS Disp.)',
      'Chonodam, KL (ESIS Disp.)',
      'Dharmadam, KL (ESIS Disp.)',
      'Azhikode, KL (ESIS Disp.)',
      'Kannur Kakkad, KL (ESIS Disp.)',
      'Kuthuparamba, KL (ESIS Disp.)',
      'Hajirappally Malappuram, KL (ESIS Disp.)',
      'Mangattuparamba, KL (ESIS Disp.)',
      'Mavoor, KL (ESIS Disp.)',
      'Payyannur, KL (ESIS Disp.)',
      'Pappinissery, KL (ESIS Disp.)',
      'Vaikkom, KL (ESIS Disp.)',
      'Dharmadam, KL (ESIS Disp.)',
      'Mala, KL (ESIS Disp.)',
    ],
    Kasaragod: ['Kasargode, KL (ESIS Disp.)', 'Kasargode, KL (ESIS Disp.)'],
    Kollam: [
      'Keralapuram, KL (ESIS Disp.)',
      'Chathannoor, KL (ESIS Disp.)',
      'Kalluvathukkal, KL (ESIS Disp.)',
      'Pooyappally, KL (ESIS Disp.)',
      'Anchal, KL (ESIS Disp.)',
      'Asramam, KL (ESIS Disp.)',
      'Chavara, KL (ESIS Disp.)',
      'Kilikollur, KL (ESIS Disp.)',
      'Kottiyam, KL (ESIS Disp.)',
      'Pattathanam, KL (ESIS Disp.)',
      'Punalur, KL (ESIS Disp.)',
      'Ramankulangara, KL (ESIS Disp.)',
      'Vilakudy, KL (ESIS Disp.)',
      'Kulasekharapuram, KL (ESIS Disp.)',
      'Kadakkal, KL (ESIS Disp.)',
      'Mylom, KL (ESIS Disp.)',
      'Mynagappally, KL (ESIS Disp.)',
      'Mulavana, KL (ESIS Disp.)',
      'Nedumpana, KL (ESIS Disp.)',
      'Poruvazhy, KL (ESIS Disp.)',
      'Perinad, KL (ESIS Disp.)',
      'Parippally, KL (ESIS Disp.)',
      'Puthoor, KL (ESIS Disp.)',
      'Sadanandapuram, KL (ESIS Disp.)',
      'Sooranad, KL (ESIS Disp.)',
      'Thodiyoor, KL (ESIS Disp.)',
      'Thrippalazhikom, KL (ESIS Disp.)',
      'Thrikkovilvattom, KL (ESIS Disp.)',
      'Pattazhy, KL (ESIS Disp.)',
      'Mavelikkara, KL (ESIS Disp.)',
      'Chandamukku, KL (ESIS Disp.)',
      'N.Vazhakulam, KL (ESIS Disp.)',
      'Palakkad, KL (ESIS Disp.)',
      'Vilakudy, KL (ESIS Disp.)',
      'Anchal, KL (ESIS Disp.)',
      'Asramam, KL (ESIS Disp.)',
      'Chathannoor, KL (ESIS Disp.)',
      'Chavara, KL (ESIS Disp.)',
      'Perinad, KL (ESIS Disp.)',
      'Thrippalazhikom, KL (ESIS Disp.)',
      'Kottayam, KL (ESIS Disp.)',
      'Mylom, KL (ESIS Disp.)',
      'Kadakkal, KL (ESIS Disp.)',
      'Kalluvathukkal, KL (ESIS Disp.)',
      'Kilikollur, KL (ESIS Disp.)',
      'Kottiyam, KL (ESIS Disp.)',
      'Chandamukku, KL (ESIS Disp.)',
      'Kottakkal, KL (ESIS Disp.)',
      'Kulasekharapuram, KL (ESIS Disp.)',
      'Thrikkovilvattom, KL (ESIS Disp.)',
      'Mulavana, KL (ESIS Disp.)',
      'Moovattupuzha, KL (ESIS Disp.)',
      'Mynagappally, KL (ESIS Disp.)',
      'Nedumpana, KL (ESIS Disp.)',
      'Parippally, KL (ESIS Disp.)',
      'Pattathanam, KL (ESIS Disp.)',
      'Pattazhy, KL (ESIS Disp.)',
      'Ettumanoor, KL (ESIS Disp.)',
      'Pooyappally, KL (ESIS Disp.)',
      'Poruvazhy, KL (ESIS Disp.)',
      'Punalur, KL (ESIS Disp.)',
      'Puthoor, KL (ESIS Disp.)',
      'Ramankulangara, KL (ESIS Disp.)',
      'Sachivothamapuram, KL (ESIS Disp.)',
      'Sadanandapuram, KL (ESIS Disp.)',
      'Sooranad, KL (ESIS Disp.)',
      'Thodiyoor, KL (ESIS Disp.)',
      'Keralapuram, KL (ESIS Disp.)',
    ],
    Kottayam: [
      'Ettumanoor, KL (ESIS Disp.)',
      'Kottayam, KL (ESIS Disp.)',
      'Sachivothamapuram, KL (ESIS Disp.)',
      'Vadavathoor, KL (ESIS Disp.)',
      'Velloor, KL (ESIS Disp.)',
      'Vaikkom, KL (ESIS Disp.)',
      'Changanassery, KL (ESIS Disp.)',
      'Velloor, KL (ESIS Disp.)',
      'Pala, KL(ESIS Disp.)',
      'Kanjirapally, KL(ESIS Disp.)',
    ],
    Kozhikode: [
      'Chakkrothukulam, KL (ESIS Disp.)',
      'Chalappuram, KL (ESIS Disp.)',
      'Eranjipalam, KL (ESIS Disp.)',
      'Cheruvannur, KL (ESIS Disp.)',
      'Chungam, KL (ESIS Disp.)',
      'Meenchanda, KL (ESIS Disp.)',
      'Bypore Cheruvannur, KL (ESIS Disp.)',
      'Kunnathupalam, KL (ESIS Disp.)',
      'Mavoor, KL (ESIS Disp.)',
      'Chemmancherry, KL (ESIS Disp.)',
      'Puthiyara, KL (ESIS Disp.)',
      'Kainatty Vadakara, KL (ESIS Disp.)',
      'Chalappuram, KL (ESIS Disp.)',
      'Cheruvannur, KL (ESIS Disp.)',
      'Meenchanda, KL (ESIS Disp.)',
      'Chungam, KL (ESIS Disp.)',
      'Vadavathoor, KL (ESIS Disp.)',
      'Kunnathupalam, KL (ESIS Disp.)',
      'Chemmancherry, KL (ESIS Disp.)',
      'Puthiyara, KL (ESIS Disp.)',
      'Aloor, KL (ESIS Disp.)',
      'Chonodam, KL (ESIS Disp.)',
      'Kainatty Vadakara, KL (ESIS Disp.)',
      'Mukkam, KL (ESIS Disp.)',
    ],
    Malappuram: [
      'Kottakkal, KL (ESIS Disp.)',
      'Kuttipuram, KL (ESIS Disp.)',
      'Hajirappally Malappuram, KL (ESIS Disp.)',
      'Nilambur, KL (ESIS Disp.)',
      'Vazhakkad, KL (ESIS Disp.)',
      'Kuttipuram, KL (ESIS Disp.)',
      'Nilambur, KL (ESIS Disp.)',
      'Valapattanam, KL (ESIS Disp.)',
      'Vazhakkad, KL (ESIS Disp.)',
      'Perinthalmanna, KL(ESIS Disp.)',
      'Manjery, KL(ESIS Disp.)',
      'DCBO - Thazhekode',
    ],
    Palakkad: [
      'Walayar Chandrapuram, KL (ESIS Disp.)',
      'Palakkad, KL (ESIS Disp.)',
      'Ottapalam, KL (ESIS Disp.)',
      'Chittoor, KL (ESIS Disp.)',
      'Parali, KL (ESIS Disp.)',
      'Kanjikode, KL (ESIS Disp.)',
      'Shornur, KL (ESIS Disp.)',
      'Walayar Chandrapuram, KL (ESIS Disp.)',
      'Mele chowa, KL (ESIS Disp.)',
      'Ottapalam, KL (ESIS Disp.)',
      'Kanjikode, KL (ESIS Disp.)',
      'Shornur, KL (ESIS Disp.)',
      'Alathur, KL (ESIS Disp.)',
    ],
    Pathanamthitta: [
      'Enathu, KL (ESIS Disp.)',
      'Kadampanadu, KL (ESIS Disp.)',
      'Thiruvalla, KL (ESIS Disp.)',
      'Enathu, KL (ESIS Disp.)',
      'Kadampanadu, KL (ESIS Disp.)',
      'Parali, KL (ESIS Disp.)',
      'Pathanamthitta , KL (ESIS Disp)',
    ],
    Thiruvananthapuram: [
      'Kovalam, KL (ESIS Disp.)',
      'Attingal, KL (ESIS Disp.)',
      'Balaramapuram, KL (ESIS Disp.)',
      'Chacka, KL (ESIS Disp.)',
      'Karamana, KL (ESIS Disp.)',
      'Kazhakkuttam, KL (ESIS Disp.)',
      'Kilimanur, KL (ESIS Disp.)',
      'Neyyattinkara, KL (ESIS Disp.)',
      'Navaikulam, KL (ESIS Disp.)',
      'Madavoor, KL (ESIS Disp.)',
      'Peroorkada, KL (ESIS Disp.)',
      'ESI Dispensary Nedumangad',
      'Nedumangad, KL (ESIS Disp.)',
    ],
    Thrissur: [
      'Koratty, KL (ESIS Disp.)',
      'Chalakkudy, KL (ESIS Disp.)',
      'Chavakkad, KL (ESIS Disp.)',
      'Irinjalakkuda, KL (ESIS Disp.)',
      'Aloor, KL (ESIS Disp.)',
      'Karuvannur, KL (ESIS Disp.)',
      'Wadakkancherry, KL (ESIS Disp.)',
      'Kunnamkulam, KL (ESIS Disp.)',
      'Mulamkunnathukavu, KL (ESIS Disp.)',
      'Ollur, KL (ESIS Disp.)',
      'Mala, KL (ESIS Disp.)',
      'Poonkunnam, KL (ESIS Disp.)',
      'Alagappanagar, KL (ESIS Disp.)',
      'Kuttanellur, KL (ESIS Disp.)',
      'Olarikkara, KL (ESIS Disp.)',
      'Alagappanagar, KL (ESIS Disp.)',
      'Chalakkudy, KL (ESIS Disp.)',
      'Irinjalakkuda, KL (ESIS Disp.)',
      'Karuvannur, KL (ESIS Disp.)',
      'Koratty, KL (ESIS Disp.)',
      'Changanassery, KL (ESIS Disp.)',
    ],
    Wayanad: ['ESI DISPENSARY KALPETTA'],
  },
  Lakshadweep: {
    Lakshadweep: [],
  },
  'Madhya Pradesh': {
    Agar: [],
    Alirajpur: [],
    Anuppur: [],
    'Ashok Nagar': [],
    Balaghat: [],
    Barwani: [],
    Betul: [],
    Bhind: ['Malanpur, MP (ESIS Disp.)'],
    Bhopal: [
      'New Subhashnagar, Bhopal, MP (ESIS Disp.)',
      'Etwara, Bhopal, MP (ESIS Disp.)',
      'BHEL, Bhopal, MP (ESIS Disp.)',
      'Amlai, MP (ESIS Disp.)',
      'BHEL, Bhopal, MP (ESIS Disp.)',
      'Etwara, Bhopal, MP (ESIS Disp.)',
      'Malanpur, MP (ESIS Disp.)',
      'New Subhashnagar, Bhopal, MP (ESIS Disp.)',
    ],
    Burhanpur: [
      'Lalbagh, Burhanpur, MP (ESIS Disp.)',
      'Lalbagh, Burhanpur, MP (ESIS Disp.)',
    ],
    Chhatarpur: [],
    Chhindwara: ['DCBO - Chhindwara, MP (ESIC DCBO)'],
    Damoh: [],
    Datia: [],
    Dewas: [],
    Dhar: [
      'Pithampur 1-2, MP (ESIS Disp.)',
      'Pithampur 3-4, MP (ESIS Disp.)',
      'Pithampur 3-4, MP (ESIS Disp.)',
      'Pithampur 1-2, MP (ESIS Disp.)',
    ],
    Dindori: [
      'Pithampur 1-2, MP (ESIS Disp.)',
      'Pithampur 3-4, MP (ESIS Disp.)',
      'Pithampur 3-4, MP (ESIS Disp.)',
      'Pithampur 1-2, MP (ESIS Disp.)',
    ],
    Guna: [
      'Pithampur 1-2, MP (ESIS Disp.)',
      'Pithampur 3-4, MP (ESIS Disp.)',
      'Pithampur 3-4, MP (ESIS Disp.)',
      'Pithampur 1-2, MP (ESIS Disp.)',
    ],
    Gwalior: [
      'Birlanagar No 1, Gwalior, MP (ESIS Disp.)',
      'DD Nagar, Gwalior, MP (ESIS Disp.)',
      'Phalke Bajar, Gwalior, MP (ESIS Disp.)',
      'Jawahar Colony, Gwalior, MP (ESIS Disp.)',
      'Murar, Gwalior, MP (ESIS Disp.)',
      'Gola Ka mandir, Gwalior, MP (ESIS Disp.)',
      'Birlanagar No 1, Gwalior, MP (ESIS Disp.)',
      'DD Nagar, Gwalior, MP (ESIS Disp.)',
      'Gola Ka mandir, Gwalior, MP (ESIS Disp.)',
      'Jawahar Colony, Gwalior, MP (ESIS Disp.)',
      'Murar, Gwalior, MP (ESIS Disp.)',
      'Phalke Bajar, Gwalior, MP (ESIS Disp.)',
    ],
    Harda: [],
    Hoshangabad: ['DCBO - Hoshangabad'],
    Indore: [
      'Nehrunagar, Indore, MP (ESIS Disp.)',
      'Mill Area, Indore, MP (ESIS Disp.)',
      'Radhaswami, Indore, MP (ESIS Disp.)',
      'Rajmohalla, Indore, MP (ESIS Disp.)',
      'Marimata Chouhara, Indore, MP (ESIS Disp.)',
      'Pardeshipura Comm.Hall, Indore, MP (ESIS Disp.)',
      'Radhaswami, Indore, MP (ESIS Disp.)',
      'Pardeshipura Comm.Hall, Indore, MP (ESIS Disp.)',
      'Marimata Chouhara, Indore, MP (ESIS Disp.)',
      'Manglia Dugh Dairy Sangh Colony, MP (Disp.)',
      'Nehrunagar, Indore, MP (ESIS Disp.)',
      'Mill Area, Indore, MP (ESIS Disp.)',
      'Rajmohalla, Indore, MP (ESIS Disp.)',
    ],
    Jabalpur: [
      'Ghamapura, Jabalpur, MP (ESIS Disp.)',
      'Write Town, Jabalpur, MP (ESIS Disp.)',
      'Hathital, Jabalpur, MP (ESIS Disp.)',
      'Adhartal, Jabalpur, MP (ESIS Disp.)',
      'Adhartal, Jabalpur, MP (ESIS Disp.)',
      'Ghamapura, Jabalpur, MP (ESIS Disp.)',
      'Hathital, Jabalpur, MP (ESIS Disp.)',
      'Write Town, Jabalpur, MP (ESIS Disp.)',
      'Beawar, RJ (ESIS Disp.)',
    ],
    Jhabua: [],
    Katni: [
      'Gayatrinagar, Katni, MP (ESIS Disp.)',
      'Niwar, Katni, MP (ESIS Disp.)',
      'Gayatrinagar, Katni, MP (ESIS Disp.)',
      'Niwar, Katni, MP (ESIS Disp.)',
    ],
    'Khandwa (East Nimar)': ['DCBO - Khandwa, MP (ESIC DCBO)'],
    'Khargone (West Nimar)': ['DCBO-Sanawad'],
    Mandla: [],
    Mandsaur: [
      'Nai Abadi, Mandsaur, MP (ESIS Disp.)',
      'Nai Abadi, Mandsaur, MP (ESIS Disp.)',
    ],
    Morena: [
      'Nai Abadi, Mandsaur, MP (ESIS Disp.)',
      'Nai Abadi, Mandsaur, MP (ESIS Disp.)',
    ],
    Narsinghpur: [],
    Neemuch: [],
    Niwari: [],
    Panna: [],
    Raisen: [
      'Indiranagar, Mandideep, MP (ESIS Disp.)',
      'Satlapur, Mandideep, MP (ESIS Disp.)',
      'Indiranagar, Mandideep, MP (ESIS Disp.)',
      'Satlapur, Mandideep, MP (ESIS Disp.)',
    ],
    Rajgarh: [],
    Ratlam: [
      'Polo Ground, Ratlam, MP (ESIS Disp.)',
      'Jawaharnagar, Ratlam, MP (ESIS Disp.)',
      'Jawaharnagar, Ratlam, MP (ESIS Disp.)',
      'Polo Ground, Ratlam, MP (ESIS Disp.)',
    ],
    Rewa: ['DCBO - Rewa'],
    Sagar: ['Sagar, MP (ESIS Disp.)', 'Sagar, MP (ESIS Disp.)', 'DCBO - Bina'],
    Satna: [
      'Satna Cement Works, MP (ESIS Disp.)',
      'Satna Cement Works, MP (ESIS Disp.)',
    ],
    Sehore: [],
    Seoni: [],
    Shahdol: ['Amlai, MP (ESIS Disp.)'],
    Shajapur: ['DCBO-Shajapur, MP (ESIS Disp.)'],
    Sheopur: ['DCBO-Shajapur, MP (ESIS Disp.)'],
    Shivpuri: ['DCBO-Shajapur, MP (ESIS Disp.)'],
    Sidhi: [],
    Singrauli: ['DCBO - Singrauli'],
    Tikamgarh: ['DCBO - Singrauli'],
    Ujjain: [
      'Birlagram, Nagda, MP (ESIS Disp.)',
      'Nagda Mandi, Nagda, MP (ESIS Disp.)',
      'Desainagar, Ujjain, MP (ESIS Disp.)',
      'Agar Road, Ujjain, MP (ESIS Disp.)',
      'Birlagram, Nagda, MP (ESIS Disp.)',
      'Nagda Mandi, Nagda, MP (ESIS Disp.)',
      'Agar Road, Ujjain, MP (ESIS Disp.)',
      'Desainagar, Ujjain, MP (ESIS Disp.)',
    ],
    Umaria: [],
    Vidisha: [],
  },
  Maharashtra: {
    Ahmednagar: [],
    Akola: [
      'D 2 Akola Harihar Peth, MH (ESIS Disp.)',
      'D 3 MIDC Akola, MH (ESIS Disp.)',
      'D 1 Ramdas Peth, Akola, MH (ESIS Disp.)',
      'MIDC Akola, MH (ESIS Disp.)',
    ],
    Amrawati: ['Amravati, MH (ESIS Disp.)', 'Nandgaon Peth, MH (ESIS Disp.)'],
    Aurangabad: [
      'D 4 Chikalthana, Aurangabad, MH (ESIS Disp.)',
      'D 3 HUDCO, Aurangabad, MH (ESIS Disp.)',
      'D 2 Aurangabad, MH (ESIS Disp.)',
      'D 1 Waluj, Aurangabad, MH (ESIC Disp.)',
      'DCBO - WALUJ',
      'Gangapur, MH (ESIS Disp.)',
      'Shendra, MH (ESIS Disp.)',
      'Paithan, MH (ESIS Disp.)',
    ],
    Beed: ['DCBO-Beed, MH (ESIC Disp.)'],
    Bhandara: ['DCBO - BHANDARA'],
    Buldhana: ['DCBO - Khamgaon'],
    Chandrapur: [
      'Ramnagar, Chandrapur, MH (ESIS Disp.)',
      'DCBO - KORPANA',
      'Warora, MH (ESIS Disp.)',
    ],
    Dhule: ['D 1 Dhule, MH (ESIS Disp.)', 'D 2 Dhule, MH (ESIS Disp.)'],
    Gadchiroli: ['DCBO-Gadchiroli, MH (ESIC DCBO)'],
    Gondia: ['DCBO - GONDIA, MH (ESIC DCBO)', 'Tiroda, MH (ESIS Disp.)'],
    Hingoli: [],
    Jalgaon: [
      'Amalner, Jagaon, MH (ESIS Disp.)',
      'Chalisgaon, Jagaon, MH (ESIS Disp.)',
      'D 2 MIDC, Jalgaon, MH (ESIS Disp.)',
      'D 1 Jalgaon, MH (ESIS Disp.)',
    ],
    Jalna: ['DCBO - Jalna'],
    Kolhapur: ['DCBO - Jalna'],
    Latur: ['DCBO - Latur'],
    'Mumbai City': [
      'Chembur, MH (ESIS Disp.)',
      'Andheri, MH (ESIS Disp.)',
      'Dharavi, MH (ESIS Disp.)',
      'Charkop, Kandivali(W), MH (ESIS Disp.)',
      'Mulund(W), MH (ESIS Disp.)',
      'Parel, MH (ESIS Disp.)',
      'Vile Parle(W), MH (ESIS Disp.)',
      'Worli Central Medical Drug Center, MH (ESIS CMS)',
      'DCBO - Colaba',
    ],
    'Mumbai Suburban': [],
    Nagpur: [
      'Butibori, MH (ESIS Disp.)',
      'Dattatraynagar, Nagpur, MH (ESIS Disp.)',
      'Bagadganj, Nagpur, MH (ESIS Disp.)',
      'Gandhinagar, Nagpur, MH (ESIS Disp.)',
      'Gaddi Godam Chowk, Nagpur, MH (ESIS Disp.)',
      'Kamptee, Nagpur, MH (ESIS Disp.)',
      'Kukade, Nagpur, MH (ESIS Disp.)',
      'Somwari Peth, Nagpur, MH (ESIS Disp.)',
      'Hanumannagar, Nagpur, MH (ESIS Disp.)',
      'Higna Road, Nagpur, MH (ESIS Disp.)',
      'Nandanvan Layout, Nagpur, MH (ESIS Disp.)',
      'Pachpawli, Nagpur, MH (ESIS Disp.)',
      'Mahal, Nagpur, MH (ESIS Disp.)',
      'Ganesh Peth, Nagpur, MH (ESIS Disp.)',
      'Wadi, Nagpur, MH (ESIS Disp.)',
      'Butibori 2, MH (ESIS Disp.)',
      'Kalmeshwar, MH (ESIS Disp.)',
      'Umred, MH (ESIS Disp.)',
    ],
    Nanded: [
      'D 1 Nanded, MH (ESIS Disp.)',
      'D 2 Nanded, MH (ESIS Disp.)',
      'D 3 Nanded, MH (ESIS Disp.)',
    ],
    Nandurbar: [],
    Nashik: [
      'Ambad, Nasik, MH (ESIS Disp.)',
      'Ashokstumbh, Nasik, MH (ESIS Disp.)',
      'Lekhanagar, CIDCO, MH (ESIS Disp.)',
      'Nasik Road, MH (ESIS Disp.)',
      'Satpur, MH (ESIS Disp.)',
      'DCBO - Sinnar',
      'Ghoti , MH (ESIC Disp.)',
      'Dindori , MH (ESIC Disp.)',
      'Ahamadnagar, MH (ESIS Disp.)',
    ],
    Osmanabad: [
      'Ambad, Nasik, MH (ESIS Disp.)',
      'Ashokstumbh, Nasik, MH (ESIS Disp.)',
      'Lekhanagar, CIDCO, MH (ESIS Disp.)',
      'Nasik Road, MH (ESIS Disp.)',
      'Satpur, MH (ESIS Disp.)',
      'DCBO - Sinnar',
      'Ghoti , MH (ESIC Disp.)',
      'Dindori , MH (ESIC Disp.)',
      'Ahamadnagar, MH (ESIS Disp.)',
    ],
    Palghar: [
      'DCBO - Palghar',
      'Boisar, MH (ESIS Disp.)',
      'Wada, MH (ESIS)',
      'Vasai, MH (ESIS)',
    ],
    Parbhani: [],
    Pune: [
      'Chinchwad, MH (ESIS Disp.)',
      'Gadital, Hadapsar, MH (ESIS Disp.)',
      'Bhosari, MH (ESIS Disp.)',
      'Wagholi, MH (ESIS Disp.)',
      'Shirur, MH (ESIS Disp.)',
      'Saswad, MH (ESIS Disp.)',
      'Sanaswadi, MH (ESIS Disp.)',
      'Ranjangaon, MH (ESIS Disp.)',
      'Rajgurunagar, MH (ESIS Disp.)',
      'Lonawala, MH (ESIS Disp.)',
      'Hinjawadi, MH (ESIS Disp.)',
      'Daund, MH (ESIS Disp.)',
      'Chakan, MH (ESIS Disp.)',
      'Baramati, MH (ESIS Disp.)',
      'Talegaon, MH (ESIS Disp.)',
      'Pirangut, MH (ESIS Disp.)',
      'Alandi, MH (ESIS Disp.)',
      'Uruli Kanchan, MH (ESIS Disp.)',
      'Khed Shivapur, MH (ESIS Disp.)',
      'Mulshi, MH (ESIS)',
      'Kurkumbh, MH (ESIS)',
    ],
    Raigad: [
      'DCBO - Panvel,MH (ESIC DCBO)',
      'Khopoli, MH (ESIS Disp.)',
      'Alibag, MH (ESIS Disp.)',
      'Kharghar, MH (ESIS)',
      'Khalapur, MH (ESIS)',
      'Nhava-Shewa, MH (ESIS)',
    ],
    Ratnagiri: [
      'DCBO - Panvel,MH (ESIC DCBO)',
      'Khopoli, MH (ESIS Disp.)',
      'Alibag, MH (ESIS Disp.)',
      'Kharghar, MH (ESIS)',
      'Khalapur, MH (ESIS)',
      'Nhava-Shewa, MH (ESIS)',
    ],
    Sangli: [
      'Miraj, MH (ESIS Disp.)',
      'Kupwad, MH (ESIS Disp.)',
      'Rajawada Chowk, Sangli, MH (ESIS Disp.)',
      'DCBO - SANGLI',
    ],
    Satara: [
      'Miraj, MH (ESIS Disp.)',
      'Kupwad, MH (ESIS Disp.)',
      'Rajawada Chowk, Sangli, MH (ESIS Disp.)',
      'DCBO - SANGLI',
    ],
    Sindhudurg: ['DCBO-Sindhudurg, MH (ESIC Disp.)'],
    Solapur: [
      'Barshi, MH (ESIS Disp.)',
      'Laxmi peth, Solapur, MH (ESIS Disp.)',
      'Mahatma Phule Market, Solapur, MH (ESIS Disp.)',
      'Samaj Kalyan Dispensary, MH (ESIS Disp.)',
      'Chincholi, MH (ESIS)',
    ],
    Thane: [
      'Barshi, MH (ESIS Disp.)',
      'Laxmi peth, Solapur, MH (ESIS Disp.)',
      'Mahatma Phule Market, Solapur, MH (ESIS Disp.)',
      'Samaj Kalyan Dispensary, MH (ESIS Disp.)',
      'Chincholi, MH (ESIS)',
    ],
    Wardha: ['Haganghat, Nagpur, MH (ESIS Disp.)', 'DCBO - Wardha'],
    Washim: ['DCBO-Washim, MH (ESIC DCBO)'],
    Yavatmal: ['DCBO - YAVATMAL'],
  },
  Manipur: {
    Bishnupur: [],
    Chandel: [],
    Churachandpur: [],
    'Imphal East': [],
    'Imphal West': ['ESIC Dispensary - Imphal'],
    Jiribam: [],
    Kakching: [],
    Kamjong: [],
    Kangpokpi: [],
    Noney: [],
    Pherzawl: [],
    Senapati: [],
    Tamenglong: [],
    Thoubal: [],
    Ukhrul: [],
  },
  Meghalaya: {
    'East Garo Hills': [],
    'East Khasi Hills': [],
    'Jaintia Hills': [],
    'North Garo Hills': [],
    'Ri-Bhoi': [],
    'South Garo Hills': [],
    'South West Garo Hills': [],
    'South West Khasi Hills': [],
    'West Garo Hills': [],
    'West Jaintia Hills': [],
    'West Khasi Hills': [],
  },
  Mizoram: {
    Aizawl: ['Aizwal, MZ (ESIS Disp.)'],
    Champhai: [],
    Kolasib: [],
    Lawngtlai: [],
    Lunglei: [],
    Mamit: [],
    Saiha: [],
    Serchhip: [],
  },
  Nagaland: {
    Dimapur: ['Dimapur, NG (ESIS Disp.)'],
    Kiphire: [],
    Kohima: [],
    Longleng: [],
    Mokokchung: ['Mokokchung,NL(ESIS Disp.)'],
    Mon: [],
    Peren: [],
    Phek: [],
    Tuensang: [],
    Wokha: [],
    Zunheboto: [],
  },
  Odisha: {
    Angul: [
      'Angul, OR (ESIS Disp.)',
      'ESI Dispensary Kaniha',
      'Jharsuguda, OR (ESIS Disp.)',
      'FCI, OR (ESIS Disp.)',
      'Hirakud, OR (ESIS Disp.)',
      'Kalunga, OR (ESIS Disp.)',
      'Kansbahal, OR (ESIS Disp.)',
      'Kuarmunda, OR (ESIS Disp.)',
      'Rourkela, OR (ESIS Disp.)',
      'Rajgangpur, OR (ESIS Disp.)',
      'Sambalpur, OR (ESIS Disp.)',
      'IDL, OR (ESIS Disp.)',
      'Kerei, OR (ESIS Disp.)',
      'Sonepur, OR (ESIS Disp.)',
      'Chhendipada, OR(ESIS Disp.)',
    ],
    'Baleswar (Balasore)': [
      'Balgopalpur, OR (ESIS Disp.)',
      'Chhanpur, OR (ESIS Disp.)',
      'Balasore, OR (ESIS Disp.)',
      'Balgopalpur, OR (ESIS Disp.)',
      'Balasore, OR (ESIS Disp.)',
      'Chhanpur, OR (ESIS Disp.)',
      'Baripada, OR (ESIS Disp.)',
    ],
    'Bargarh (Baragarh)': [
      'Balgopalpur, OR (ESIS Disp.)',
      'Chhanpur, OR (ESIS Disp.)',
      'Balasore, OR (ESIS Disp.)',
      'Balgopalpur, OR (ESIS Disp.)',
      'Balasore, OR (ESIS Disp.)',
      'Chhanpur, OR (ESIS Disp.)',
      'Baripada, OR (ESIS Disp.)',
    ],
    Bhadrak: ['Randia, OR (ESIS Disp.)', 'Charmpa, OR (ESIS Disp.)'],
    'Bolangir (Balangir)': [
      'Bolangir, OR (ESIS Disp.)',
      'Bolangir, OR (ESIS Disp.)',
    ],
    'Boudh (Bauda)': [],
    Cuttack: [
      'Choudwar, OR (ESIS Disp.)',
      'Khapuria, OR (ESIS Disp.)',
      'Jagatpur, OR (ESIS Disp.)',
      'Barang, OR (ESIS Disp.)',
      'T.P.M, OR (ESIS Disp.)',
      'ESI DISPENSARY RAJABAGICHA',
      'ESI Dispensary Tangi (Bhagatpur)',
      'Khuntuni, OR(ESIS Disp.)',
    ],
    'Debagarh (Deogarh)': [
      'Choudwar, OR (ESIS Disp.)',
      'Khapuria, OR (ESIS Disp.)',
      'Jagatpur, OR (ESIS Disp.)',
      'Barang, OR (ESIS Disp.)',
      'T.P.M, OR (ESIS Disp.)',
      'ESI DISPENSARY RAJABAGICHA',
      'ESI Dispensary Tangi (Bhagatpur)',
      'Khuntuni, OR(ESIS Disp.)',
    ],
    Dhenkanal: [
      'Choudwar, OR (ESIS Disp.)',
      'Khapuria, OR (ESIS Disp.)',
      'Jagatpur, OR (ESIS Disp.)',
      'Barang, OR (ESIS Disp.)',
      'T.P.M, OR (ESIS Disp.)',
      'ESI DISPENSARY RAJABAGICHA',
      'ESI Dispensary Tangi (Bhagatpur)',
      'Khuntuni, OR(ESIS Disp.)',
    ],
    Gajapati: [],
    Ganjam: [],
    Jagatsinghpur: [],
    'Jajapur (Jajpur)': [
      'Jajpur road, OR (ESIS Disp.)',
      'Dhanmandal, OR (ESIS Disp.)',
      'Duburi, OR (ESIS Disp.)',
      'Duburi, OR (ESIS Disp.)',
    ],
    Jharsuguda: [
      'Brajrajnagar, OR (ESIS Disp.)',
      'Jharsuguda, OR (ESIS Disp.)',
      'ESI Dispensary, Badmal (Lapanga)',
    ],
    Kalahandi: [],
    Kandhamal: [],
    Kendrapara: [],
    'Kendujhar (Keonjhar)': [
      'Barbil, OR (ESIS Disp.)',
      'Brahmanipal, OR (ESIS Disp.)',
      'Barbil, OR (ESIS Disp.)',
      'Brahmanipal, OR (ESIS Disp.)',
    ],
    Khordha: [
      'Khurda, OR (ESIS Disp.)',
      'SAHIDNAGAR, OR (ESIS Disp.)',
      'Chandrasekharpur, OR (ESIS Disp.)',
      'Bhubaneswar, OR (ESIS Disp.)',
      'Khurda, OR (ESIS Disp.)',
      'Puri, OR (ESIS Disp.)',
      'ESIS Dispensary- Badmal',
    ],
    Koraput: [
      'Jeypore, OR (ESIS Disp.)',
      'ESI Dispensary, Damanjodi',
      'Jeypore, OR (ESIS Disp.)',
      'ESI DISPENSARY DAMANJODI(ESIS Disp.)',
    ],
    Malkangiri: [],
    Mayurbhanj: ['Baripada, OR (ESIS Disp.)'],
    Nabarangpur: ['Baripada, OR (ESIS Disp.)'],
    Nayagarh: [],
    Nuapada: [],
    Puri: ['Puri, OR (ESIS Disp.)'],
    Rayagada: ['Puri, OR (ESIS Disp.)'],
    Sambalpur: ['Puri, OR (ESIS Disp.)'],
    'Subarnapur (Sonepur)': ['Puri, OR (ESIS Disp.)'],
    'Sundargarh (Sundergarh)': [
      'FCI, OR (ESIS Disp.)',
      'Kansbahal, OR (ESIS Disp.)',
      'Kalunga, OR (ESIS Disp.)',
      'Rourkela, OR (ESIS Disp.)',
      'Rajgangpur, OR (ESIS Disp.)',
      'Kerei, OR (ESIS Disp.)',
      'IDL, OR (ESIS Disp.)',
      'Kuarmunda, OR (ESIS Disp.)',
      'CISF, OR (ESIS Disp.)',
      'Randia, OR (ESIS Disp.)',
      'Jajpur road, OR (ESIS Disp.)',
      'CISF, OR (ESIS Disp.)',
      'Charmpa, OR (ESIS Disp.)',
      'DCBO - Vedvyas',
    ],
  },
  Puducherry: {
    Karaikal: [
      'Nedungadu, PY (ESIS Disp.)',
      'T.R.Pattinam, PY (ESIS Disp.)',
      'Nedungadu, PY (ESIS Disp.)',
      'T.R.Pattinam, PY (ESIS Disp.)',
      'Palloor, Mahe, PY (ESIS Disp.)',
    ],
    Mahe: [],
    Puducherry: [],
    Yanam: [],
  },
  Punjab: {
    Amritsar: [
      'Majitha Rd, Amritsar, PB (ESIS Disp.)',
      'Chheharata, Amritsar Dist., PB (ESIS Disp.)',
      'Goindwal Sahib, Amritsar Dist., PB (ESIS Disp.)',
      'Manawala Kalan, Amritsar Dist., PB (ESIS Disp.)',
      'Taran Taran, Amritsar Dist., PB (ESIS Disp.)',
      'Verka, Amritsar Dist., PB (ESIS Disp.)',
      'D 2, Malwa Mills, Barnala, PB (ESIS Disp.)',
    ],
    Barnala: [
      'D 1, Malwa Mills, Barnala, PB (ESIS Disp.)',
      'Barnala, PB (ESIC Model Disp.)',
      'DCBO-Barnala',
    ],
    Bathinda: [
      'D 1, Malwa Mills, Barnala, PB (ESIS Disp.)',
      'Barnala, PB (ESIC Model Disp.)',
      'DCBO-Barnala',
    ],
    Faridkot: ['Kotkapura, Faridkot Dist., PB (ESIS Disp.)'],
    'Fatehgarh Sahib': [
      'Mandi Gobindgarh, PB (ESIS Disp.)',
      'Kukad Majra, Mandi Gobindgarh, PB (ESIS Disp.)',
      'Sirhind, PB (ESIS Disp.)',
    ],
    Fazilka: [],
    Firozpur: ['Abohar, PB (ESIS Disp.)', 'Firozpur, PB (ESIC DCBO)'],
    Gurdaspur: [
      'Umarpura, Batala, PB (ESIS Disp.)',
      'Dhariwal, Gurdaspur Dist., PB (ESIS Disp.)',
      'Dinanagar, Gurdaspur Dist., PB (ESIS Disp.)',
    ],
    Hoshiarpur: [
      'Chhohal, Hoshiarpur Dist., PB (ESIS Disp.)',
      'Nasrala, Hoshiarpur Dist., PB (ESIS Disp.)',
      'Purhirah, Hoshiarpur Dist., PB (ESIS Disp.)',
      'Saila Khurd, Hoshiarpur, PB (ESIS Disp.)',
    ],
    Jalandhar: [
      'Basri Ganj, Jallandhar, PB (ESIS Disp.)',
      'Dada Colony, Jalandhar, PB (ESIS Disp.)',
      'Jalandar, Goraya, PB (ESIS Disp.)',
      'Sahid Udham Singh Nagar, Jallandhar, PB (ESIS Disp.)',
      'Ladowali Road, Jallandhar, PB (ESIS Disp.)',
      'Avaidnagar, Jallandhar, PB (ESIS Disp.)',
      'Philluar, Jalandar, PB (ESIS Disp.)',
    ],
    Kapurthala: [
      'Hamira, Jagatjitnagar, Kapurthala, PB (ESIS Disp.)',
      'Kapurthala, PB (ESIS Disp.)',
      'Civil Hospital complex, Phagwara, PB (ESIS Disp.)',
      'Opp. JCT Mill, Phagwara, PB (ESIS Disp.)',
    ],
    Ludhiana: [
      'Khanna, PB (ESIS Disp.)',
      'Capt. Wazir Singh Road dispensary-11 Ludhiana, PB (ESIS Disp.)',
      'Vardhman Mills dispensary no-2 , Ludhiana, PB (ESIS Disp.)',
      'Focal Point dispensary no-3, Ludhiana, PB (ESIS Disp.)',
      'Village Hiran machhiwara, Ludhiana, PB (ESIS Disp.)',
      'Field Ganj dispensary no-8, Ludhiana, PB (ESIS Disp.)',
      'Gurmukh Singh & Sons dispensary no-10, Ludhiana, PB (ESIS Disp.)',
      'Jalandhar by-pass dispensary no-12, Ludhiana, PB (ESIS Disp.)',
      'Gill Road Dispensary no-7, Jantanagar, Ludhiana, PB (ESIS Disp.)',
      'Jugiana Road dispensary no-6, Ludhiana, PB (ESIS Disp.)',
      'D 1 ESI Hospital campus, Ludhiana, PB (ESIS Disp.)',
      'D 4 ESI Hospital campus, Ludhiana, PB (ESIS Disp.)',
      'Ralsonnagar dispensary no-5, Ludhiana, PB (ESIS Disp.)',
      'Machiwara, PB (ESIS Disp.)',
    ],
    Mansa: [],
    Moga: ['Nanaknagri, Moga, PB (ESIS Disp.)'],
    Pathankot: ['Pathankot, PB (ESIS Disp.)'],
    Patiala: [
      'Civil Hospital, Nabha, PB (ESIS Disp.)',
      'Bishannagar, Bahadurgarh, Patiala, PB (ESIS Disp.)',
      'Dera Bassi, Patiala Dist., PB (ESIS Disp.)',
      'Nahar Factory, Lalru, Patiala, PB (ESIS Disp.)',
      'Punjabibagh, Patiala, PB (ESIS Disp.)',
      'DCBO-Rajpura, PB (ESIC Disp.)',
      'Samana,PB (ESIS Disp.)',
    ],
    Rupnagar: [
      'Asron, Near Ropar, PB (ESIS Disp.)',
      'Nuhon, Near Ropar, PB (ESIS Disp.)',
    ],
    Sangrur: [
      'Ahmedgarh, PB (ESIS Disp.)',
      'Lalbazar, Malerkotla, PB (ESIS Disp.)',
      'Akbarpur, Sangrur Dist., PB (ESIS Disp.)',
      'Jitwal Kalan, Sangrur Dist., PB (ESIS Disp.)',
      'Sangrur, PB (ESIS Disp.)',
      'Dhuri,PB (ESIC Disp.)',
    ],
    'SAS NAGAR (MOHALI)': [
      'Kharar, PB (ESIS Disp.)',
      'Near Saini Market, Lalru, PB (ESIS Disp.)',
      'Phase-II, Mohali, PB (ESIS Disp.)',
      'Phase-VII, Mohali, PB (ESIS Disp.)',
    ],
    'Shahid Bhagat Singh Nagar': ['Banah, Nawan Sahar Dist., PB (ESIS Disp.)'],
    'Taran Taran': [],
  },
  Rajasthan: {
    Ajmer: [
      'Kalabagh, Ajmer, RJ (ESIS Disp.)',
      'Sangram Bhawan, Ajmer, RJ (ESIS Disp.)',
      'Pinglow House, Kishangarh, RJ (ESIS Disp.)',
      'Beawar, RJ (ESIS Disp.)',
      'Kalabagh, Ajmer, RJ (ESIS Disp.)',
      'Sangram Bhawan, Ajmer, RJ (ESIS Disp.)',
      'Pinglow House, Kishangarh, RJ (ESIS Disp.)',
      'Makrana, RJ (ESIS Disp.)',
      'DCBO - Ajmer',
    ],
    Alwar: [
      'Bhiwadi, RJ (ESIS Disp.)',
      'Kala Kua, Alwar, RJ (ESIS Disp.)',
      'Matsya, Alwar, RJ (ESIS Disp.)',
      'Matila, RJ (ESIS Disp.)',
      'Neemrana, RJ (ESIS Disp.)',
      'Khushkera, RJ (ESIC Disp.)',
      'Bhiwadi, RJ (ESIS Disp.)',
      'Kala Kua, Alwar, RJ (ESIS Disp.)',
      'Matsya, Alwar, RJ (ESIS Disp.)',
      'Alwar Road, Matila, RJ (ESIS Disp.)',
      'Neemrana, RJ (ESIS Disp.)',
    ],
    Banswara: ['Banswara, RJ (ESIS Disp.)', 'Banswara, RJ (ESIS Disp.)'],
    Baran: ['Banswara, RJ (ESIS Disp.)', 'Banswara, RJ (ESIS Disp.)'],
    Barmer: ['Balotra, RJ (ESIS Disp.)'],
    Bharatpur: [],
    Bhilwara: [
      'Ranjeetnagar, Bharatpur, RJ (ESIS Disp.)',
      'Super Bazar, Bharatpur, RJ (ESIS Disp.)',
      'Ranjeetnagar, Bharatpur, RJ (ESIS Disp.)',
      'Super Bazar, Bharatpur, RJ (ESIS Disp.)',
    ],
    Bikaner: [
      'Ranjeetnagar, Bharatpur, RJ (ESIS Disp.)',
      'Super Bazar, Bharatpur, RJ (ESIS Disp.)',
      'Ranjeetnagar, Bharatpur, RJ (ESIS Disp.)',
      'Super Bazar, Bharatpur, RJ (ESIS Disp.)',
    ],
    Bundi: [],
    Chittorgarh: [
      'Chanderia, Chittorgarh, RJ (ESIS Disp.)',
      'Chanderia, Chittorgarh, RJ (ESIC Disp.)',
      'Shambhupura, Chittorgarh, RJ (ESIS Disp.)',
    ],
    Churu: ['DCBO - Churu, RJ (ESIS Disp.)'],
    Dausa: ['DCBO - Churu, RJ (ESIS Disp.)'],
    Dholpur: [
      'Pratapnagar colony, Dholpur, RJ (ESIS Disp.)',
      'Pratapnagar colony, Dholpur, RJ (ESIS Disp.)',
      'Old General Hospital, Dungarpur, RJ (ESIS Disp.)',
    ],
    Dungapur: [
      'Old General Hospital, Dungarpur, RJ (ESIS Disp.)',
      'Durgapore-I, WB (ESIS Disp.)',
    ],
    Ganganagar: [
      'Old General Hospital, Dungarpur, RJ (ESIS Disp.)',
      'Durgapore-I, WB (ESIS Disp.)',
    ],
    Hanumangarh: ['Hanumangarh, RJ (ESIS Disp.)'],
    Jaipur: [
      'Bagru, Jaipur, RJ (ESIS Disp.)',
      'Bapunagar, Jaipur, RJ (ESIS Disp.)',
      'Chandpole Bazar, Jaipur, RJ (ESIS Disp.)',
      'Jaitpura, Jaipur, RJ (ESIS Disp.)',
      'Kanota, Jaipur, RJ (ESIS Disp.)',
      'DISP No 4 Ajmer Road, Jaipur, RJ (ESIS Disp.)',
      'DISP No 8 Laxminagar, Jaipur, RJ (ESIS Disp.)',
      'Malviyanagar, Jaipur, RJ (ESIS Disp.)',
      'Pratapnagar, Jaipur, RJ (ESIS Disp.)',
      'Ramganj Chopa, Jaipur, RJ (ESIS Disp.)',
      'Shastrinagar, Jaipur, RJ (ESIS Disp.)',
      'Shivajinagar, Civil Lines, Jaipur, RJ (ESIS Disp.)',
      'Near Tar Ghar, Jaipur, RJ (ESIS Disp.)',
      'Vki Area, Jaipur, RJ (ESIS Disp.)',
      'State Directorate, RJ (ESIS SD)',
      'Kukas,Jaipur,RJ (ESIS Disp.)',
      'Bagru, Jaipur, RJ (ESIS Disp.)',
      'Bapunagar, Jaipur, RJ (ESIS Disp.)',
      'Chandpole Bazar, Jaipur, RJ (ESIS Disp.)',
      'Jaitpura, Jaipur, RJ (ESIS Disp.)',
      'Kanota, Jaipur, RJ (ESIS Disp.)',
      'Ajmer Road, Jaipur, RJ (ESIS Disp.)',
      'Laxminagar, Jaipur, RJ (ESIS Disp.)',
      'Malviyanagar, Jaipur, RJ (ESIS Disp.)',
      'Pratapnagar, Jaipur, RJ (ESIS Disp.)',
      'Ramganj Chopa, Jaipur, RJ (ESIS Disp.)',
      'Shastrinagar, Jaipur, RJ (ESIS Disp.)',
      'Shivajinagar, Civil Lines, Jaipur, RJ (ESIS Disp.)',
      'Near Tar Ghar, Jaipur, RJ (ESIS Disp.)',
      'Vki Area, Jaipur, RJ (ESIS Disp.)',
      'Reegus, RJ (ESIS Disp.)',
      'Tonk, RJ (ESIS Disp.)',
      'Kukas, RJ (ESIS Disp.)',
      'Janana Hospital, Kotputli, RJ (ESIS Disp.)',
      'Kaladera, Jaipur, RJ (ESIS Disp.)',
      'Sarnadunagar, Jaipur, RJ (ESIS Disp.)',
      'Janana Hospital, Kotputli, RJ (ESIS Disp.)',
      'Sarnadungar, Jaipur, RJ (ESIS Disp.)',
    ],
    Jaisalmer: ['Transport Nagar, Jaisalmer, RJ (ESIS Disp.)'],
    Jalore: [],
    Jhalawar: ['Bhawani Mandi, RJ (ESIS Disp.)'],
    Jhunjhunu: ['Bhawani Mandi, RJ (ESIS Disp.)'],
    Jodhpur: [
      'Akashwani Bhawan, Jodhpur, RJ (ESIS Disp.)',
      'Basni, Jodhpur, RJ (ESIS Disp.)',
      'Churaha Boranada, Jodhpur, RJ (ESIS Disp.)',
      'Kamla Nehru Nagar, Jodhpur, RJ (ESIS Disp.)',
      'Medical College, Jodhpur, RJ (ESIS Disp.)',
      'Jodhpur 2, RJ (ESIS Disp.)',
      'Balotra, RJ (ESIS Disp.)',
      'Akashwani Bhawan, Jodhpur, RJ (ESIS Disp.)',
      'Basni, Jodhpur, RJ (ESIS Disp.)',
      'Opposite SBBJ, Boranada,Jodhpur, RJ (ESIS Disp.)',
      'Kamla Nehru Nagar, Jodhpur, RJ (ESIS Hosp.)',
      'Medical College, Jodhpur, RJ (ESIS Disp.)',
      'DCBO - Jodhpur',
    ],
    Karauli: [],
    Kota: [
      'Industrial Area, Kota, RJ (ESIS Disp.)',
      'ESI Hospital Campus, Kota, RJ (ESIS Disp.)',
      'Rampura Kota, RJ (ESIS Disp.)',
      'Bhawani Mandi, RJ (ESIS Disp.)',
      'Industrial Area, Kota, RJ (ESIS Disp.)',
      'ESI Hospital Campus, Kota, RJ (ESIS Disp.)',
      'Rampura Kota, RJ (ESIS Disp.)',
    ],
    Nagaur: [
      'Industrial Area, Kota, RJ (ESIS Disp.)',
      'ESI Hospital Campus, Kota, RJ (ESIS Disp.)',
      'Rampura Kota, RJ (ESIS Disp.)',
      'Bhawani Mandi, RJ (ESIS Disp.)',
      'Industrial Area, Kota, RJ (ESIS Disp.)',
      'ESI Hospital Campus, Kota, RJ (ESIS Disp.)',
      'Rampura Kota, RJ (ESIS Disp.)',
    ],
    Pali: [
      'Industrial Area, Kota, RJ (ESIS Disp.)',
      'ESI Hospital Campus, Kota, RJ (ESIS Disp.)',
      'Rampura Kota, RJ (ESIS Disp.)',
      'Bhawani Mandi, RJ (ESIS Disp.)',
      'Industrial Area, Kota, RJ (ESIS Disp.)',
      'ESI Hospital Campus, Kota, RJ (ESIS Disp.)',
      'Rampura Kota, RJ (ESIS Disp.)',
    ],
    Pratapgarh: [],
    Rajsamand: [
      'New Aabadi, Gunjol, RJ (ESIS Disp.)',
      'Bhilwara Road, Kankroli, RJ (ESIS Disp.)',
      'Gulabpura, RJ (ESIS Disp.)',
    ],
    'Sawai Madhopur': [],
    Sikar: ['Reegus, RJ (ESIS Disp.)', 'Neem Ka Thana, Sikar, RJ (ESIS Disp.)'],
    Sirohi: [
      'Reegus, RJ (ESIS Disp.)',
      'Neem Ka Thana, Sikar, RJ (ESIS Disp.)',
    ],
    Tonk: ['Tonk, RJ (ESIS Disp.)'],
    Udaipur: [
      'Ashoknagar, Udaipur, RJ (ESIS Disp.)',
      'Dabok, Udaipur, RJ (ESIS Disp.)',
      'Madri, Udaipur, RJ (ESIS Disp.)',
      'Rishbdev, Udaipur, RJ (ESIS Disp.)',
      'Sukher, Udaipur, RJ (ESIS Disp.)',
      'New Aabadi, Gunjol, RJ (ESIS Disp.)',
      'Bhilwara Road, Kankroli, RJ (ESIS Disp.)',
      'Ashoknagar, Udaipur, RJ (ESIS Disp.)',
      'Dabok, Udaipur, RJ (ESIS Disp.)',
      'Madri, Udaipur, RJ (ESIS Disp.)',
      'Rishbdev, Udaipur, RJ (ESIS Disp.)',
      'Sukher, Udaipur, RJ (ESIS Disp.)',
    ],
  },
  Sikkim: {
    'East Sikkim': ['Rangpo (ESIS Dispensary)', 'Tadong (ESIS Dispensary)'],
    'North Sikkim': ['Rangpo (ESIS Dispensary)', 'Tadong (ESIS Dispensary)'],
    'South Sikkim': ['Rangpo (ESIS Dispensary)', 'Tadong (ESIS Dispensary)'],
    'West Sikkim': ['Rangpo (ESIS Dispensary)', 'Tadong (ESIS Dispensary)'],
  },
  Tamilnadu: {
    'East Sikkim': ['Rangpo (ESIS Dispensary)', 'Tadong (ESIS Dispensary)'],
    'North Sikkim': [],
    Chennai: [
      'Adayar, TN (ESIS Disp.)',
      'Avadi, TN (ESIS Disp.)',
      'Ambattur I, TN (ESIS Disp.)',
      'Ambattur II, TN (ESIS Disp.)',
      'Anna Salai Chetpet, TN (ESIS Disp.)',
      'Choolai, TN (ESIS Disp.)',
      'Egmore, TN (ESIS Disp.)',
      'Gummidipoondi, TN (ESIS Disp.)',
      'Harbour, TN (ESIS Disp.)',
      'Kilpauk-I, TN (ESIS Disp.)',
      'Kilpauk, TN (ESIS Disp.)',
      'Kodambakkam, TN (ESIS Disp.)',
      'Kodungaiyur, TN (ESIS Disp.)',
      'Kondithope I, TN (ESIS Disp.)',
      'Kondithope II, TN (ESIS Disp.)',
      'Korattur, TN (ESIS Disp.)',
      'Manali, TN (ESIS Disp.)',
      'Mylapore, TN (ESIS Disp.)',
      'Nandambakkam, TN (ESIS Disp.)',
      'Pallavaram, TN (ESIS Disp.)',
      'Perambur I, TN (ESIS Disp.)',
      'Perambur II, TN (ESIS Disp.)',
      'Perambur III, TN (ESIS Disp.)',
      'Poonamallee, TN (ESIS Disp.)',
      'Red Hills, TN (ESIS Disp.)',
      'Saidapet I, TN (ESIS Disp.)',
      'Saidapet II, TN (ESIS Disp.)',
      'Sembium, TN (ESIS Disp.)',
      'Sriperumputhur, TN (ESIS Disp.)',
      'Thiruvottiyur, TN (ESIS Disp.)',
      'Thiruvottiyur II, TN (ESIS Disp.)',
      'Thiruvottiyur III, TN (ESIS Disp.)',
      'Triplicane, TN (ESIS Disp.)',
      'Tondiarpet, TN (ESIS Disp.)',
      'Tondiarpet II, TN (ESIS Disp.)',
      'Villiwakkam, TN (ESIS Disp.)',
      'ESI Dispensary - Oragadam',
      'ESI dispensary, Padapai',
      'ESI dispensary -Panjati',
    ],
    Coimbatore: [
      'Adayar, TN (ESIS Disp.)',
      'Avadi, TN (ESIS Disp.)',
      'Ambattur I, TN (ESIS Disp.)',
      'Ambattur II, TN (ESIS Disp.)',
      'Anna Salai Chetpet, TN (ESIS Disp.)',
      'Choolai, TN (ESIS Disp.)',
      'Egmore, TN (ESIS Disp.)',
      'Gummidipoondi, TN (ESIS Disp.)',
      'Harbour, TN (ESIS Disp.)',
      'Kilpauk-I, TN (ESIS Disp.)',
      'Kilpauk, TN (ESIS Disp.)',
      'Kodambakkam, TN (ESIS Disp.)',
      'Kodungaiyur, TN (ESIS Disp.)',
      'Kondithope I, TN (ESIS Disp.)',
      'Kondithope II, TN (ESIS Disp.)',
      'Korattur, TN (ESIS Disp.)',
      'Manali, TN (ESIS Disp.)',
      'Mylapore, TN (ESIS Disp.)',
      'Nandambakkam, TN (ESIS Disp.)',
      'Pallavaram, TN (ESIS Disp.)',
      'Perambur I, TN (ESIS Disp.)',
    ],
  },
  Telangana: {
    Ariyalur: [
      'Avinashi, TN (ESIS Disp.)',
      'Chinnaiyambalayam, TN (ESIS Disp.)',
      'Coimbatore, TN (ESIS Mobile Disp.)',
      'Ganapathy, TN (ESIS Disp.)',
      'Irugur, TN (ESIS Disp.)',
      'Karamadai, TN (ESIS Disp.)',
      'Kattoor I, TN (ESIS Disp.)',
      'Kattoor II, TN (ESIS Disp.)',
      'Kuniamuthur, TN (ESIS Disp.)',
      'Madathukulam, TN (ESIS Disp.)',
      'Madukarai, TN (ESIS Disp.)',
      'Mettupalayam, TN (ESIS Disp.)',
      'Nallattipalayam, TN (ESIS Disp.)',
      'Naranapuram, TN (ESIS Disp.)',
      'Ondiputhur, TN (ESIS Disp.)',
      'Othakkalmandapam, TN (ESIS Disp.)',
      'Palladam, TN (ESIS Disp.)',
      'Pappanaickenpalayam, TN (ESIS Disp.)',
      'Peelamedu, TN (ESIS Disp.)',
      'Perianaickenpalayam, TN (ESIS Disp.)',
      'Peethappampatti, TN (ESIS Disp.)',
      'Pollachi, TN (ESIS Disp.)',
      'Pothanur, TN (ESIS Disp.)',
      'Raja Street, TN (ESIS Disp.)',
      'Ramanathapuram, TN (ESIS Disp.)',
      'Singanallur, TN (ESIS Disp.)',
      'Somanur, TN (ESIS Disp.)',
      'Sowripalayam, TN (ESIS Disp.)',
      'Sulur, TN (ESIS Disp.)',
      'Thudialur, TN (ESIS Disp.)',
      'Tiruppur I, TN (ESIS Disp.)',
      'Tiruppur II, TN (ESIS Disp.)',
      'Udumalpet, TN (ESIS Mobile Disp.)',
      'Udumalpet (static), TN (ESIS Disp.)',
      'Uppilipalayam, TN (ESIS Disp.)',
      'Vellalore, TN (ESIS Disp.)',
      'Udhagamandalam, TN (ESIS Disp.)',
      'Annur, TN(ESIC Disp)',
      'S S Kulam, TN(ESIC Disp)',
      '2/3C, Sathy Main Road',
      'Sultanpet, TN (ESIS Disp.)',
      'Valparai, TN (ESIS Disp.)',
    ],
    Chengalpattu: [],
    Hyderabad: [
      'Ameerpet, AP (ESIS Disp.)',
      'Balanagar (New), AP (ESIS Disp.)',
      'Sanat Nagar-III, AP (ESIS Disp.)',
      'Balanagar(Old), AP (ESIS Disp.)',
      'Borabanda, AP (ESIS Disp.)',
      'Chappal Bazar, AP (ESIS Disp.)',
      'Chikkadapally, AP (ESIS Disp.)',
      'Chilkalguda, AP (ESIS Disp.)',
      'Dabeerpura, AP (ESIS Disp.)',
      'Yakuthpura, AP (ESIS Disp.)',
      'Golconda, AP (ESIS Disp.)',
      'Goshamahal, AP (ESIS Disp.)',
      'Nampally, AP (ESIS Disp.)',
      'Karwan, AP (ESIS Disp.)',
      'Himmathpura, AP (ESIS Disp.)',
      'Khairatabad, AP (ESIS Disp.)',
      'Kavadiguda (New), AP (ESIS Disp.)',
      'Vidya Nagar, AP (ESIS Disp.)',
      'Ramanthapur, AP (ESIS Disp.)',
      'Old City Ramakrishna cly, AP (ESIS Disp.)',
      'Ranigunj (New) Alwal, AP (ESIS Disp.)',
      'Rezimental Bazar, AP (ESIS Disp.)',
      'Secunderabad, AP (ESIS Disp.)',
      'Sanathnagar-I, AP (ESIS Disp.)',
      'Sanathnagar-II, AP (ESIS Disp.)',
      'Tarnaka, AP (ESIS Disp.)',
      'Kukatpally, AP (ESIS Disp.)',
      'Kavadiguda, AP (ESIS Disp.)',
      'Kavadiguda Road, AP (ESIS Disp.)',
      'Moulali, AP (ESIS Disp.)',
      'Malkajgiri, AP (ESIS Disp.)',
      'Shamshabad, AP (ESIS Disp.)',
      'Ameerpet, AP (ESIS Disp.)',
      'Dabeerpura, AP (ESIS Disp.)',
      'Sanathnagar-II, AP (ESIS Disp.)',
      'Sanat Nagar-III, AP (ESIS Disp.)',
      'Kavadiguda (New), AP (ESIS Disp.)',
      'Ramnagar, AP (ESIS Disp.)',
      'Rezimental Bazar, AP (ESIS Disp.)',
      'Balanagar(Old), AP (ESIS Disp.)',
      'Chikkadapally, AP (ESIS Disp.)',
      'Golconda, AP (ESIS Disp.)',
      'Goshamahal, AP (ESIS Disp.)',
      'Himmathpura, AP (ESIS Disp.)',
      'Chappal Bazar, AP (ESIS Disp.)',
      'Karwan, AP (ESIS Disp.)',
      'Khairatabad, AP (ESIS Disp.)',
      'Kukatpally, AP (ESIS Disp.)',
      'Yakuthpura, AP (ESIS Disp.)',
      'Malkajgiri, AP (ESIS Disp.)',
      'Kavadiguda Road, AP (ESIS Disp.)',
      'Nampally, AP (ESIS Disp.)',
      'Ramanthapur, AP (ESIS Disp.)',
      'Old City Ramakrishna cly, AP (ESIS Disp.)',
      'Sanathnagar-I, AP (ESIS Disp.)',
      'Balanagar (New), AP (ESIS Disp.)',
      'Borabanda, AP (ESIS Disp.)',
      'Tarnaka, AP (ESIS Disp.)',
      'Vidya Nagar, AP (ESIS Disp.)',
      'Basanthnagar, AP (ESIS Disp.)',
      'Moulali, AP (ESIS Disp.)',
      'Kavadiguda, AP (ESIS Disp.)',
      'Chilkalguda, AP (ESIS Disp.)',
      'Secunderabad, AP (ESIS Disp.)',
      'Balanagar (New), AP (ESIS Disp.)',
      'Devapuram, AP (ESIS Disp.)',
      'DCBO - Sanathnagar',
    ],
    Jagtial: [
      'Ameerpet, AP (ESIS Disp.)',
      'Balanagar (New), AP (ESIS Disp.)',
      'Sanat Nagar-III, AP (ESIS Disp.)',
      'Balanagar(Old), AP (ESIS Disp.)',
      'Borabanda, AP (ESIS Disp.)',
      'Chappal Bazar, AP (ESIS Disp.)',
      'Chikkadapally, AP (ESIS Disp.)',
      'Chilkalguda, AP (ESIS Disp.)',
      'Dabeerpura, AP (ESIS Disp.)',
      'Yakuthpura, AP (ESIS Disp.)',
      'Golconda, AP (ESIS Disp.)',
      'Goshamahal, AP (ESIS Disp.)',
      'Nampally, AP (ESIS Disp.)',
      'Karwan, AP (ESIS Disp.)',
      'Himmathpura, AP (ESIS Disp.)',
      'Khairatabad, AP (ESIS Disp.)',
      'Kavadiguda (New), AP (ESIS Disp.)',
      'Vidya Nagar, AP (ESIS Disp.)',
      'Ramanthapur, AP (ESIS Disp.)',
      'Old City Ramakrishna cly, AP (ESIS Disp.)',
      'Ranigunj (New) Alwal, AP (ESIS Disp.)',
      'Rezimental Bazar, AP (ESIS Disp.)',
      'Secunderabad, AP (ESIS Disp.)',
      'Sanathnagar-I, AP (ESIS Disp.)',
      'Sanathnagar-II, AP (ESIS Disp.)',
      'Tarnaka, AP (ESIS Disp.)',
      'Kukatpally, AP (ESIS Disp.)',
      'Kavadiguda, AP (ESIS Disp.)',
      'Kavadiguda Road, AP (ESIS Disp.)',
      'Moulali, AP (ESIS Disp.)',
      'Malkajgiri, AP (ESIS Disp.)',
      'Shamshabad, AP (ESIS Disp.)',
      'Ameerpet, AP (ESIS Disp.)',
      'Dabeerpura, AP (ESIS Disp.)',
      'Sanathnagar-II, AP (ESIS Disp.)',
      'Sanat Nagar-III, AP (ESIS Disp.)',
      'Kavadiguda (New), AP (ESIS Disp.)',
      'Ramnagar, AP (ESIS Disp.)',
      'Rezimental Bazar, AP (ESIS Disp.)',
      'Balanagar(Old), AP (ESIS Disp.)',
      'Chikkadapally, AP (ESIS Disp.)',
      'Golconda, AP (ESIS Disp.)',
      'Goshamahal, AP (ESIS Disp.)',
      'Himmathpura, AP (ESIS Disp.)',
      'Chappal Bazar, AP (ESIS Disp.)',
      'Karwan, AP (ESIS Disp.)',
      'Khairatabad, AP (ESIS Disp.)',
      'Kukatpally, AP (ESIS Disp.)',
      'Yakuthpura, AP (ESIS Disp.)',
      'Malkajgiri, AP (ESIS Disp.)',
      'Kavadiguda Road, AP (ESIS Disp.)',
      'Nampally, AP (ESIS Disp.)',
      'Ramanthapur, AP (ESIS Disp.)',
      'Old City Ramakrishna cly, AP (ESIS Disp.)',
      'Sanathnagar-I, AP (ESIS Disp.)',
      'Balanagar (New), AP (ESIS Disp.)',
      'Borabanda, AP (ESIS Disp.)',
      'Tarnaka, AP (ESIS Disp.)',
      'Vidya Nagar, AP (ESIS Disp.)',
      'Basanthnagar, AP (ESIS Disp.)',
      'Moulali, AP (ESIS Disp.)',
      'Kavadiguda, AP (ESIS Disp.)',
      'Chilkalguda, AP (ESIS Disp.)',
      'Secunderabad, AP (ESIS Disp.)',
      'Balanagar (New), AP (ESIS Disp.)',
      'Devapuram, AP (ESIS Disp.)',
      'DCBO - Sanathnagar',
    ],
    Jangaon: [
      'Ameerpet, AP (ESIS Disp.)',
      'Balanagar (New), AP (ESIS Disp.)',
      'Sanat Nagar-III, AP (ESIS Disp.)',
      'Balanagar(Old), AP (ESIS Disp.)',
      'Borabanda, AP (ESIS Disp.)',
      'Chappal Bazar, AP (ESIS Disp.)',
      'Chikkadapally, AP (ESIS Disp.)',
      'Chilkalguda, AP (ESIS Disp.)',
      'Dabeerpura, AP (ESIS Disp.)',
      'Yakuthpura, AP (ESIS Disp.)',
      'Golconda, AP (ESIS Disp.)',
      'Goshamahal, AP (ESIS Disp.)',
      'Nampally, AP (ESIS Disp.)',
      'Karwan, AP (ESIS Disp.)',
      'Himmathpura, AP (ESIS Disp.)',
      'Khairatabad, AP (ESIS Disp.)',
      'Kavadiguda (New), AP (ESIS Disp.)',
      'Vidya Nagar, AP (ESIS Disp.)',
    ],
    'Jayashankar Bhoopalpally': [],
    'Jogulamba Gadwal': [],
    Kamareddy: [],
    Karimnagar: [],
    Khamman: [
      'Ramavaram, AP (ESIS Disp.)',
      'Khammam, AP (ESIS Disp.)',
      'Khammam, AP (ESIS Disp.)',
      'Industrial Estate, AP (ESIS Disp.)',
    ],
    'Komaram Bheem Asifabad': ['DCBO - Sirpurkaghaznagar'],
    Mahabubabad: [],
    Mahbubnagar: [
      'Kothur, AP (ESIS Disp.)',
      'Mahaboobnagar, AP (ESIS Disp.)',
      'Mahaboobnagar, AP (ESIS Disp.)',
      'Kothur, AP (ESIS Disp.)',
      'Bollaram, AP (ESIS Disp.)',
      'Bonthapally, AP (ESIS Disp.)',
      'Isnapur, AP (ESIS Disp.)',
      'Patancheru, AP (ESIS Disp.)',
      'Patighanapur, AP (ESIS Disp.)',
      'Sadasivpet, AP (ESIS Disp.)',
      'Shabashpally, AP (ESIS Disp.)',
      'Zaheerabad, AP (ESIS Disp.)',
      'Bibinagar, AP (ESIS Disp.)',
      'Choutuppal, AP (ESIS Disp.)',
      'Bhongir, AP (ESIS Disp.)',
      'Shivajinagar, AP (ESIS Disp.)',
      'Nizamabad, AP (ESIS Disp.)',
      'Shamshabad, AP (ESIS Disp.)',
      'Jadcharla ,AP (ESIS Disp.)',
      'BALANAGAR(MBNR)',
      'DCBO - Mahaboobnagar',
    ],
    Mancherial: [],
    Medak: [
      'Bollaram, AP (ESIS Disp.)',
      'Bonthapally, AP (ESIS Disp.)',
      'Isnapur, AP (ESIS Disp.)',
      'Patancheru, AP (ESIS Disp.)',
      'Patighanapur, AP (ESIS Disp.)',
      'Shabashpally, AP (ESIS Disp.)',
      'Sadasivpet, AP (ESIS Disp.)',
      'Zaheerabad, AP (ESIS Disp.)',
    ],
    Medchal: ['Jeedimetla,TS (ESIC Disp.)'],
    Mulugu: ['Jeedimetla,TS (ESIC Disp.)'],
    Nagarkurnool: [],
    Nalgoda: [
      'Bhongir, AP (ESIS Disp.)',
      'DCBO-Bibinagar, AP (ESIS Disp.)',
      'Choutuppal, AP (ESIS Disp.)',
      'MIRYALAGUDA',
    ],
    Narayanapet: [],
    Nirmal: [],
    Nizamabad: [
      'Nizamabad, AP (ESIS Disp.)',
      'Shivajinagar, AP (ESIS Disp.)',
      'DCBO - Nizamabad',
    ],
    Peddapalli: ['DCBO - Ramagundam, TS (ESIC DCBO)'],
    'Rajanna Sircilla': [],
    Rangareddy: [
      'Fathenagar, AP (ESIS Disp.)',
      'Jeedimetla-I, AP (ESIS Disp.)',
      'Koheda, AP (ESIS Disp.)',
      'Jeedimetla-II, AP (ESIS Disp.)',
      'Kattedan, AP (ESIS Disp.)',
      'Medchal, AP (ESIS Disp.)',
      'Kattedan, AP (ESIS Disp.)',
      'Cherlapally, AP (ESIS Disp.)',
      'Ranigunj (New) Alwal, AP (ESIS Disp.)',
      'SHAMEERPET',
      'IDA CHERLAPALLY',
      'DCBO - L.B. Nagar',
    ],
    Sangareddy: ['DCBO - Sadashivpeta'],
    Siddipet: [],
    Suryapet: [],
    Vikarabad: [],
    Wanaparthy: [],
    Warangal: [
      'Hanmakonda, AP (ESIS Disp.)',
      'Girmajipet, AP (ESIS Disp.)',
      'Industrial Colony, AP (ESIS Disp.)',
      'Kareemabad, AP (ESIS Disp.)',
      'Girmajipet, AP (ESIS Disp.)',
      'Hanmakonda, AP (ESIS Disp.)',
      'Industrial Colony, AP (ESIS Disp.)',
      'Kareemabad, AP (ESIS Disp.)',
      'DCBO - Warangal',
    ],
    'Warangal (Rural)': [],
    'Yadadri Bhuvanagiri': [],
  },
  Tripura: {
    Adilabad: [],
    'Bhadradri Kothagudem': [],
    Khowai: [],
    'North Tripura': [],
    Sipahijala: ['Bishramganj, TP (ESIS Disp.)'],
    'South Tripura': [],
    Unakoti: [],
    Unokoti: [],
    'West Tripura': ['Agartala, TP (ESIS Disp.)'],
  },
  'Uttar Pradesh': {
    Agra: [
      'Jeewanimandi, Agra, UP (ESIS Disp.)',
      'Under ESI Hospital, Agra, UP (ESIS Mobile A Disp.)',
      'Chhipitola, Agra, UP (ESIS Disp.)',
      'New Unit, ESI Hosp. camp., Agra, UP (ESIS Mobile Disp.)',
      'Nanuai, Agra, UP (ESIS Disp.)',
    ],
    Aligarh: [
      'Sasni, Aligarh, UP (ESIS Disp.)',
      'Hospital campus, Sasni Gate, Aligarh, UP (ESIS Disp.)',
    ],
    Allahabad: [
      'Sasni, Aligarh, UP (ESIS Disp.)',
      'Hospital campus, Sasni Gate, Aligarh, UP (ESIS Disp.)',
    ],
    'Ambedkar Nagar': [
      'Sasni, Aligarh, UP (ESIS Disp.)',
      'Hospital campus, Sasni Gate, Aligarh, UP (ESIS Disp.)',
    ],
    Amethi: ['DCBO - Amethi'],
    Amroha: ['Gajaraula, UP (ESIS Disp.)'],
    Auraiya: [],
    Azamgarh: [],
    Badaun: [],
    Bagpat: [],
    Bahraich: [],
    Ballia: [],
    Balrampur: [],
    Banda: [],
    Barabanki: [],
    Bareilly: [],
    Basti: [],
    Bijnor: [],
    Bulandshahr: [
      'Bulandshahar, UP (ESIS Disp.)',
      'Khurja, Bulandshahar, UP (ESIS Disp.)',
      'Sikandrabad, Bulandshahar, UP (ESIS Disp.)',
    ],
    Chandauli: [
      'Bulandshahar, UP (ESIS Disp.)',
      'Khurja, Bulandshahar, UP (ESIS Disp.)',
      'Sikandrabad, Bulandshahar, UP (ESIS Disp.)',
    ],
    Chitrakoot: [],
    Deoria: [],
    Etah: [],
    Etawah: ['Etawah, UP (ESIS Disp.)'],
    Faizabad: ['Etawah, UP (ESIS Disp.)'],
    Farrukhabad: ['Farukhabad, UP (ESIS Disp.)'],
    Fatehpur: ['Chaudagara, Fathehpur, UP (ESIS Disp.)'],
    Firozabad: [
      'Mobile Dispensary, Firozabad, UP (ESIS Disp.)',
      'Firozabad, UP (ESIS Disp.)',
      'Shikohabad, UP (ESIS Disp.)',
    ],
    'Gautam Buddha Nagar': [
      'Greater Noida, UP (ESIC Disp.)',
      'NEPZ Ph-II, Noida, UP (ESIC Disp.)',
      'Sec-12, Noida, UP (ESIC Disp.)',
      'Sec-57, Noida, UP (ESIC Disp.)',
    ],
    Ghaziabad: [
      'Jindalnagar, Ghaziabad, UP (ESIS Disp.)',
      'Kamlanagar, Ghaziabad, UP (ESIS Disp.)',
      'Kiran colony, Ghaziabad, UP (ESIS Disp.)',
      'Mohannagar, Ghaziabad, UP (ESIS Disp.)',
      'Pasonda, Ghaziabad, UP (ESIS Disp.)',
      'Rajnagar, Ghaziabad, UP (ESIS Disp.)',
      'Suryanagar, Ghaziabad, UP (ESIS Disp.)',
      'Govindpuri, Modinagar, UP (ESIS Disp.)',
      'Oil Mill gate, Modinagar, UP (ESIS Disp.)',
    ],
    Ghazipur: [],
    Gonda: [],
    Gorkakhpur: [],
    Hamirpur: [],
    Hardoi: ['Sandeela, UP (ESIS Disp.)'],
    'Hathras (Mahamaya Nagar)': ['Sandeela, UP (ESIS Disp.)'],
    Jalaun: [],
    'Jaunpur District': [],
    Jhansi: ['Civil lines, Jhansi, UP (ESIS Disp.)'],
    Kannauj: [],
    'Kanpur Dehat': [],
    'Kanpur Nagar': [
      'Babupurva, Kanpur, UP (ESIS Disp.)',
      'Benajhabar, Kanpur, UP (ESIS Disp.)',
      'Chamanganj, Kanpur, UP (ESIS Disp.)',
      'Chaubeypur, Kanpur, UP (ESIS Disp.)',
      'Dalelpurva, Kanpur, UP (ESIS Disp.)',
      'Govindnagar, Kanpur, UP (ESIS Disp.)',
      'Homeopathy, Govindnagar, Kanpur, UP (ESIS Disp.)',
      'Humayunbagh, Kanpur, UP (ESIS Disp.)',
      'Jajmau, Kanpur, UP (ESIS Disp.)',
      'Ayurveda, Jajmua Hospital, Kanpur, UP (ESIS Disp.)',
      'Juhi-2, K Kanpur, UP (ESIS Disp.)',
      'Juhi-3, Kanpur, UP (ESIS Disp.)',
      'Gwaltoli, Kanpur, UP (ESIS Disp.)',
      'Ayurveda, Kidwainagar, Kanpur, UP (ESIS Disp.)',
      'Homeopathy, Kidwainagar, Kanpur, UP (ESIS Disp.)',
      'Mirpur, Kanpur, UP (ESIS Disp.)',
      'Nawabganj, Kanpur, UP (ESIS Disp.)',
      'Panki, Kanpur, UP (ESIS Disp.)',
      'Ayurveda, Pandunagar, Kanpur, UP (ESIS Disp.)',
      'Pandunagar, Kanpur, UP (ESIS Mobile Disp.)',
      'Homeopathy, Pandunagar, Kanpur, UP (ESIS Disp.)',
      'Patkapur, Kanpur, UP (ESIS Disp.)',
      'Raipurva Achryanagar, Kanpur, UP (ESIS Disp.)',
      'Rambagh, Kanpur, UP (ESIS Disp.)',
      'Raniganj, Kanpur, UP (ESIS Disp.)',
      'Raniya, Kanpur, UP (ESIS Disp.)',
      'Sarvodyanagar, Kanpur, UP (ESIS Disp.)',
      'Ayurveda, Mariampur, Kanpur, UP (ESIS Disp.)',
      'Alopathy, Mariampur, UP (ESIS Disp.)',
      'Shastrinagar, Kanpur, UP (ESIS Disp.)',
    ],
    'Kanshiram Nagar': [
      'Babupurva, Kanpur, UP (ESIS Disp.)',
      'Benajhabar, Kanpur, UP (ESIS Disp.)',
      'Chamanganj, Kanpur, UP (ESIS Disp.)',
      'Chaubeypur, Kanpur, UP (ESIS Disp.)',
      'Dalelpurva, Kanpur, UP (ESIS Disp.)',
      'Govindnagar, Kanpur, UP (ESIS Disp.)',
      'Homeopathy, Govindnagar, Kanpur, UP (ESIS Disp.)',
      'Humayunbagh, Kanpur, UP (ESIS Disp.)',
      'Jajmau, Kanpur, UP (ESIS Disp.)',
      'Ayurveda, Jajmua Hospital, Kanpur, UP (ESIS Disp.)',
      'Juhi-2, K Kanpur, UP (ESIS Disp.)',
      'Juhi-3, Kanpur, UP (ESIS Disp.)',
      'Gwaltoli, Kanpur, UP (ESIS Disp.)',
      'Ayurveda, Kidwainagar, Kanpur, UP (ESIS Disp.)',
      'Homeopathy, Kidwainagar, Kanpur, UP (ESIS Disp.)',
      'Mirpur, Kanpur, UP (ESIS Disp.)',
      'Nawabganj, Kanpur, UP (ESIS Disp.)',
      'Panki, Kanpur, UP (ESIS Disp.)',
      'Ayurveda, Pandunagar, Kanpur, UP (ESIS Disp.)',
      'Pandunagar, Kanpur, UP (ESIS Mobile Disp.)',
      'Homeopathy, Pandunagar, Kanpur, UP (ESIS Disp.)',
      'Patkapur, Kanpur, UP (ESIS Disp.)',
      'Raipurva Achryanagar, Kanpur, UP (ESIS Disp.)',
      'Rambagh, Kanpur, UP (ESIS Disp.)',
      'Raniganj, Kanpur, UP (ESIS Disp.)',
      'Raniya, Kanpur, UP (ESIS Disp.)',
      'Sarvodyanagar, Kanpur, UP (ESIS Disp.)',
      'Ayurveda, Mariampur, Kanpur, UP (ESIS Disp.)',
      'Alopathy, Mariampur, UP (ESIS Disp.)',
      'Shastrinagar, Kanpur, UP (ESIS Disp.)',
    ],
    Kaushambi: [],
    Kushinagar: [],
    'Lakhimpur Kheri': [],
    Lalitpur: [],
    Lucknow: [],
    Maharajganj: [],
  },
  Uttarakhand: {
    Agra: [],
    Bageshwar: [],
    Chamoli: [],
    Champawat: [],
    Dehradun: [
      'Ajabpur Khurd, UC (ESIS Disp.)',
      'Selaqui, UC (ESIS Disp.)',
      'Mussorrie, UC (ESIS Disp.)',
      'Rishikesh, UC (ESIS Disp.)',
      'Laltappad, UC (ESIS Disp.)',
      'IT Park, UC (ESIS Disp.)',
      'Suddhowala, UC (ESIS Disp.)',
      'Nehru Colony, UC (ESIS Disp.)',
      'Doiwala, UC (ESIS Disp.)',
      'Vikas Nagar, UT (ESIS Disp.)',
      'Dehradun, UC (ESIS Disp.)',
      'Guniyal Gaon, UC (ESIS Disp.)',
    ],
    Haridwar: [
      'Ajabpur Khurd, UC (ESIS Disp.)',
      'Selaqui, UC (ESIS Disp.)',
      'Mussorrie, UC (ESIS Disp.)',
      'Rishikesh, UC (ESIS Disp.)',
      'Laltappad, UC (ESIS Disp.)',
      'IT Park, UC (ESIS Disp.)',
      'Suddhowala, UC (ESIS Disp.)',
      'Nehru Colony, UC (ESIS Disp.)',
      'Doiwala, UC (ESIS Disp.)',
      'Vikas Nagar, UT (ESIS Disp.)',
      'Dehradun, UC (ESIS Disp.)',
    ],
    Nainital: [
      'Lalkuan, UC (ESIS Disp.)',
      'Nainital, UC (ESIS Disp.)',
      'Lalkuan, UC (ESIS Disp.)',
      'Nainital, UC (ESIS Disp.)',
      'Haldwani, UC (ESIS Disp.)',
      'Ramanagar, UC (ESIS Disp.)',
    ],
    'Pauri Garhwal': [
      'Kotdwar, UC (ESIS Disp.)',
      'Kotdwar, UC (ESIS Disp.)',
      'Shrinagar, UC (ESIS Disp.)',
    ],
    Pithoragharh: [],
    Rudraprayag: [],
    'Tehri Garhwal': [],
    'Udham Singh Nagar': [],
    Uttarkashi: [],
  },
  'West Bengal': {
    Alipurduar: [],
    Bankura: [],
    Birbhum: [],
    'Cooch Behar': [],
    Darjeeling: [],
    'East Bardhaman': ['DCBO - Burdwan'],
    Hoogly: ['DCBO - Burdwan'],
    Howrah: ['DCBO - Burdwan'],
    Jalpaiguri: ['DCBO - Burdwan'],
    Jhargram: ['DCBO - Burdwan'],
    Kalimpong: ['DCBO - Burdwan'],
    Kolkata: ['DCBO - Burdwan'],
    Malda: ['DCBO - Burdwan'],
    Murshidabad: ['DCBO - Burdwan'],
    Nadia: ['DCBO - Burdwan'],
    'North 24 Pargana': ['DCBO - Burdwan'],
    'North Dinajpur': ['DCBO - Burdwan'],
    'Paschim Midnapore': ['DCBO - Burdwan'],
    'Purba Medinapore': ['DCBO - Burdwan'],
    Purulia: ['DCBO - Burdwan'],
    'South 24 Parganas': ['DCBO - Burdwan'],
    'South Dinajpur': ['DCBO - Burdwan'],
    'West Bardhaman': ['DCBO - Burdwan'],
  },
};
